### ISSUE TITLE
Tab Data : Tab Analysis : new : Compare : tab pouvant se rétrécir 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#10]
Comme pour Areas ici 

![comparetab](https://user-images.githubusercontent.com/22026724/35333463-26eeae6a-010f-11e8-8013-76c99f1e3811.png)

![comparetab2](https://user-images.githubusercontent.com/22026724/35333469-2bfd1c8e-010f-11e8-8258-5237215c2c37.png)

Le tab Compare doit pouvoir se rétrécir. 

![compare](https://user-images.githubusercontent.com/22026724/35333480-3377a54c-010f-11e8-9ae2-99e14fe5d1d5.png)

**Comment by payementcha** [comment]
oui

**Comment by jalazawa** [comment]
Fait
