### ISSUE TITLE
Chronique : supprimer les deux chroniques hydraulique 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#100]
Supprimer la chronique hydraulique lac et hydraulique fil de l'eau 

![supprimer_hydraulique](https://user-images.githubusercontent.com/22026724/37286291-cbf4ef02-2601-11e8-8400-e0c7be98140d.png)

demande initiale de @fredbreant et validé par @demoulinflo

**Comment by bthieurmel** [comment]
ok.

**Comment by jalazawa** [comment]
Merci

**Comment by demoulinflo** [comment]
Suite au point avec Frédéric, nous avions décidé de supprimer les chroniques de production. 
Je vous envoie le fichier "ColumnNames" à jour par mail.

**Comment by bthieurmel** [comment]
Fait, en attendant de la déployer à nouveau. Petite question concernant les congestions des liens : actuellement je ne récupère pas ``CONG. PROB +`` et  ```CONG. PROB -`` mais uniquement la congestion calculée = ``(`CONG. PROB +` + `CONG. PROB -`)/100``. c'est ok pour vous ?

Et on est d'accord que cela impacte uniquement l'onglet *chroniques* et que l'on garde les camemberts sur la carte ?

**Comment by demoulinflo** [comment]
Ok pour la congestion.
Impact uniquement sur l'onglet "chroniques" (pas d'impact sur la carte).
