### ISSUE TITLE
Analyse détaillée - Maj. mineure (texte, ...)

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#105]
**Tous les onglets**
-> Supprimer les boutons proposant le téléchargement sur les graphiques.
-> Mettre à jour le texte affiché avec les fichiers joints (correction + description des évènements "type")

**Onglet "Chroniques"**
-> A simplifier en supprimant la table de "liens" (trop compliqué...)
---> Données / Table : Champ masqué
---> Table : Champ masqué, "nœuds" sélectionné par défaut
---> Eléments : Champ masqué, "fr" sélectionné par défaut

**Onglet "Carte"**
-> Modifier la valeur du pas de temps par défaut à "horaire"

[resultats_carte.zip](https://github.com/rte-antares-rpackage/bpN/files/1871385/resultats_carte.zip)
[resultats_chroniques.zip](https://github.com/rte-antares-rpackage/bpN/files/1871386/resultats_chroniques.zip)
[resultats_echanges.zip](https://github.com/rte-antares-rpackage/bpN/files/1871387/resultats_echanges.zip)
[resultats_production.zip](https://github.com/rte-antares-rpackage/bpN/files/1871388/resultats_production.zip)

**Comment by bthieurmel** [comment]
Ok. Dispo demain après MAJ de l'appli.
