### ISSUE TITLE
Analyse détaillée - Pas de temps 

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#106]
1/ Pas de temps "annuel" 
Le pas de temps "annuel" provoque des comportements bizarres (disparition du champ "période" sur Firefox, sélection du 1er juillet sur IE... et aucune donnée affichée !)

2/ Pas de temps "hebdo" et "mensuel"
Si sélection du pas de temps hebdo -> impossible de sélectionner du 24 au 30 juin 
Si sélection du pas de temps mensuel -> impossible les dates au delà du 1er juin
J'imagine que c'est parce que ce sont les "derniers" 1er jour de la semaine et 1er jour du mois

Ce n'est pas clair pour l'utilisateur...

En conséquence : 
-> Supprimer le pas de temps "annuel" (ça n'apporte pas grand chose de toute façon)
-> Peut-on initialiser la valeur de la période sur l'année entière (1er juillet -> 29 juin) si on sélectionne le pas de temps "hebdo" ou "mensuel" ? Si non, on supprime également...

En complément, quand on affiche les données sur une plus grande période, les mois en abscisse sont en anglais. Je crois qu'on en avait déjà parlé, je ne sais plus si c'est modifiable...

**Comment by demoulinflo** [comment]
1/ C'est validé, on supprime !

2/ On initie sur l'année, ce sera plus clair. 

Pour clarifier le fonctionnement par évènement / par tirage, il faudrait que : 
-> Si type de sélection = "par évènement"
---> pas de temps = horaire (non modifiable)
---> période = semaine de l'evt (non modifiable)
---> tirage = tirage evt  (non modifiable)
-> Si type de sélection = "par tirage"
----> tous les champs sont modifiables

Je croyais avoir créé une issue à ce sujet mais je ne la trouve plus !

Ok pour la légende sur les graphes, c'est noté.

**Comment by bthieurmel** [comment]
Ok. J'étais parti plus ou moins la dessus. Par contre j'avais laissé "hebdomadaire" pour les événements. Un avis ?

**Comment by demoulinflo** [comment]
Pour tracer nos échanges par mail, uniquement "horaire" pour les évènements

**Comment by demoulinflo** [comment]
Pour le reste, la solution implémentée se rapproche en effet de ma demande initiale.
Il reste cependant des comportements non intuitifs, par exemple : 
-> pouvoir changer le pas de temps en sélection "par evt" 
-> ne pas pouvoir repasser du mode "par evt" au mode "par tirage" si le pas de temps diffère de "horaire"

Il me semble qu'il est plus simple de "masquer" des champs plutôt que de les rendre "non modifiables".
En reprenant la demande initiale, le comportement final pourrait être le suivant : 

-> Sélection "par evt" (sélection par défaut)
---> pas de temps = horaire, champ masqué
---> tirage = nom de l'evt (par défaut "hiver moyen")
---> période = période de l'evt, champ masqué
-> Sélection "par tirage"
---> pas de temps = horaire par défaut 
---> tirage = numéro du tirage (= le tirage de la sélection par évènement précédente)
---> période = période (= la période de la sélection par évènement précédente)
--------> si pas de temps différent de horaire, on initialise la période sur l'année

Pour résumer
--> Sélection par evt, l'utilisateur ne peut modifier que l'evt
--> Sélection par tirage, tous les champs sont modifiables, il sont initialisés par défaut avec les paramètres de l'evt précédent (ou par des paramètres fixes si plus simpl mais c'est déjà ce fonctionenement me semble t il)
--> Si l'utilisateur repasse en mode par evt, on réinitialise sur le paramétrage de l'evt "hiver moyen". 

A dispo pour échanger.

**Comment by bthieurmel** [comment]
ça n'y paraît peut-être pas mais c'est un des  les plus longs pour ne pas dire chia... à changer, avec pleins de cas / bugs à gérer....

Dans ta vision, on aurait donc la box "Sélection" au-dessus de pas de temps et des pas de temps dépendant de cette sélection.

Je regarde cela....

**Comment by demoulinflo** [comment]
Yep, je connais ca, je sais que c'est toujours un peu tordu.
Je peux essayer de faire un shéma rapidement, ça permettra de voir si je n'ai rien oublié.

**Comment by bthieurmel** [comment]
Je pense personnellement que c'est dommage que de ne garder que horaire, et que certaines personnes ont envie de voir directement un "résumé" des valeurs pour jours ou autres....

Je regarderai cela plus tard.

**Comment by demoulinflo** [comment]
Si on arrive à garder une navigation intuitive je suis pour aussi...
A minima il faut que l'utilisateur puisse revenir sur la sélection "par tirage" sans avoir sélectionné horaire.

**Comment by bthieurmel** [comment]
C'est ok sauf pour ce point : 

 Si l'utilisateur repasse en mode par evt, on réinitialise sur le paramétrage de l'evt "hiver moyen".

ou l'événement reste au-niveau du dernier tirage sélectionné. Pas trop grave je pense.

Je déploye.

**Comment by demoulinflo** [comment]
C'est top !
