### ISSUE TITLE
Tab Data : Tab Analysis : edit : Compare : options partagées entre prodStack, exchangesStack et tsPlot 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#11]
Changer les 3 select box prodStack, exchangesStack et tsPlot par un seul select box. 

![compare](https://user-images.githubusercontent.com/22026724/35333636-be4745f6-010f-11e8-90f9-e9c6ecd6b41d.png)

Les options de comparaisons seront partagées entre ces 3 graphiques. 

Seulement deux options seront présentes. 

mcYear et areas 

Pour prodStack, cela veut dire qu'on veut comparer soit avec l'argument mcYear soit avec areas. 

Pour exchangesStack, cela veut dire qu'on veut comparer soit avec l'argument mcYear soit avec **area**. 

Pour tsPlot, rien à faire, cet onglet doit être supprimé.

**Comment by payementcha** [comment]
oui
un seul compare pour tous les onglets

**Comment by jalazawa** [comment]
Fait
