### ISSUE TITLE
Tab tsPlot : à supprimer 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#12]
Cet onglet doit être supprimé.

 ça te vas @payementcha ?

**Comment by payementcha** [comment]
Ok pour la première version, on supprime

**Comment by jalazawa** [comment]
Finalement, on supprime l'onglet.

**Comment by jalazawa** [comment]
Finalement, on ne supprime pas l'onglet. 

Je clos.
