### ISSUE TITLE
Tab prodStack  exchangesStack : delete :  supprimer l'option average de l'argument mcYear 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#13]
supprimer l'option average de l'argument mcYear pour les deux onglets. 

![averagedelete](https://user-images.githubusercontent.com/22026724/35334231-f18a2f94-0111-11e8-9252-827d40a1796d.png)

**Comment by payementcha** [comment]
ok

**Comment by jalazawa** [comment]
Fait
