### ISSUE TITLE
application : new : ajouter trois onglets sur les hypothèses 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#14]
Un rajouter 3 onglets 
1.  hypothèses de production 
2. hypothèses de consommation
3. hypothèses interconnexion
 
Les arguments des graphiques à faire varier : 

- areas  (fr, de, nl etc.) @payementcha des arguments à rajouter ? 

On utilisera des diagrammes en baton représentant l'évolution des capacités installées de production et de consommation. 

Les données importées seront des csv. 

@payementcha est-ce que tu peux faire deux captures d'écrans des deux graphiques ?

**Comment by jalazawa** [comment]
Les données à traiter sont de faible volume. 

La taille du fichier des hypothèses de production est de 1Mo. 

Voilà un exemple de graphique 

![exemple_production_hypo](https://user-images.githubusercontent.com/22026724/35378332-ae37dfec-01b2-11e8-8cf6-60d9ba035812.png)

Sur l'axe des X = les années 
Sur l'axe des Y = des capacités en MW 

Le type de graphique sera un diagramme en baton. 

Le seul argument à faire varier est le pays (contrairement à l'image, filière, date etc. ne seront pas à faire varier).

**Comment by jalazawa** [comment]
@payementcha je te laisse rajouter les infos pour les hypothèses de consommation et d’interconnexion.

**Comment by payementcha** [comment]
Tant qu'on a pas le go pour publier je préfère te les envoyer par email ok ? @jalazawa

**Comment by bthieurmel** [comment]
J'ai implémenté une V0 pour la production depuis l'onglet "global". Question : 

- reste-on la-dessus ?
- filtres supplémentaires (sur les trajectories par exemples ?, pour le moment tout est pris....)
- plus d'informations sur les autres onglets
- ....

**Comment by payementcha** [comment]
Merci, ça a une bonne tête graphique.
 
Deux options : 
- filtre supplémentaire pour sélectionner la trajectoire$ (un filtre pour les enr, un filtre pour le thermique)
- lors du chargement de l'étude dans  "données", le filtrage se fait en conséquence
Je préfère la deuxième option suivant la complexité
A+

**Comment by bthieurmel** [comment]
Ok. Pour la deuxième option, cela dépend de ce que vous voulez comme utilisation / sélection des études: 

- L'utilisateur doit-il avoir le droit de sélectionner plusieurs études ? Si oui, la gestion automatique des filtres peut être compliquée.
- Si l'utilisateur ne peut sélectionner qu'une étude finalement, on peut l'implémenter relativement simplement. Et du coup changer l'interface de l'onglet "Données".

**Comment by payementcha** [comment]
J'ai l'impression que la sélection d'une seule étude est suffisante. 
Si ça permet de simplifier l'onglet Données je suis preneur. 
Je t'envoie la table de correspondance pour les hypothèses de production entre étude et filtre.

**Comment by jalazawa** [comment]
Je voudrais bien confirmer une chose. 

Est-ce que l'utilisateur pourra toujours choisir dans le bouton "Résultats/Etudes" plusieurs études ? 

Les noms ayant changés, j'espère ne pas etre HS.

**Comment by jalazawa** [comment]
FAIT
