### ISSUE TITLE
application : Tab Data : Tab import Data 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#17]
Supprimer le Tab import Data 
Importer par défaut 10 (ou 12) jeu de données H5 (si possible tous les fichiers h5 contenus dans un dossier) 

Donc supprimer ce tab 

![tabimport](https://user-images.githubusercontent.com/22026724/35335023-8ef00162-0114-11e8-91b9-edac4b2aa73c.png)

Importer 12 fichiers h5 

![tabanalysis](https://user-images.githubusercontent.com/22026724/35335060-a9b5e0d4-0114-11e8-9beb-d7030ffffda0.png)

**Comment by payementcha** [comment]
oui

**Comment by jalazawa** [comment]
Est-ce qu'on peut avoir plusieurs études H5 @demoulinflo  ?

**Comment by demoulinflo** [comment]
J'ai envoyé les coupes 36 pour les 4 scénarios à Benoit.
@jalazawa je te les transfère par poste restante.

Je génère les H5 "light" demain.

**Comment by jalazawa** [comment]
Le tab import a bien été modifié comme indiqué.
