### ISSUE TITLE
ProdStack : new : initialisation des paramètres du graphique 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#20]
mcYear = 1 
title = @payementcha quel titre donné  ? 
dateRange = toute l'année @payementcha tu confirmes ? 
stack = eco2mix 
unit = MWh 
areas = fr 
legend = check on (OK) 
stepPlot = à supprimer comme indique ici #1 
De plus cette option ne doit pas être activée. 
drawPoints = à supprimer comme indique ici #1 
De plus cette option ne doit pas être activée.

**Comment by payementcha** [comment]
mcYear = 1
 **title = Production
 dateRange = Date **
 stack = eco2mix
 unit = MWh
 areas = fr
 legend = check on (OK)
 stepPlot = à supprimer comme indique ici #1
 De plus cette option ne doit pas être activée.
 drawPoints = à supprimer comme indique ici #1
 De plus cette option ne doit pas être activée.

**Comment by jalazawa** [comment]
Fait
