### ISSUE TITLE
exchangesStack : new : initialisation des paramètres du graphique

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#21]
mcYear = 1
title = @payementcha quel titre donné ?
dateRange = toute l'année @payementcha tu confirmes ?
unit = MWh
area = fr
legend = check on (OK)
stepPlot = à supprimer comme indique ici #15 
De plus cette option ne doit pas être activée.
drawPoints = à supprimer comme indique ici #15 
De plus cette option ne doit pas être activée.

**Comment by payementcha** [comment]
OK

mcYear = 1
 **title = Echanges
 dateRange = Date**
 unit = MWh
 area = fr
 legend = check on (OK)
 stepPlot = à supprimer comme indique ici #15
 De plus cette option ne doit pas être activée.
 drawPoints = à supprimer comme indique ici #15
 De plus cette option ne doit pas être activée.

**Comment by jalazawa** [comment]
Finalement on garde les options 

Voilà la dernière mise à jour de l'initialisation 

mcYear = 1
title = Echanges
dateRange = Date
unit = MWh
area = fr
legend = check on (OK)
stepPlot = Cette option doit être activée. 
drawPoints = Cette option ne doit pas être activée.

**Comment by jalazawa** [comment]
Fait
