### ISSUE TITLE
plotMap : new : initialisation des paramètres du graphique #20

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#22]
type = By time id 
dateRange = toute l'année @payementcha tu confirmes ?
Areas 
1.  color = LOAD 
2. size = "NUCLEAR, LIGNITE, COAL, GAS, OIL, MIX. FUEL, MISC. DTG, H. STOR, WIND, SOLAR, H. ROR, MISC. NDG" 
@payementcha je propose de ne pas mettre la colonne PSP dans size ? ok ? 

3.  miniplot, areaCharType = pieChart 
3.  miniplot, sizeMiniPlot --> option ON (check box OK) 

Links 
Rien à faire

**Comment by payementcha** [comment]
Ca me va, plus d'information à #32 
L'idée est de limiter encore plus les options de l'utilisateur pour la carte

**Comment by bthieurmel** [comment]
Fait. Mis également le pas de temps par défaut en journalier. En effet, en horaire, cela fait vraiment beaucoup de données envoyées au client pour la visualisation animée de la carte.... A débattre pour faire un choix.

**Comment by jalazawa** [comment]
Data : Journalier

**Comment by jalazawa** [comment]
Fait.
