### ISSUE TITLE
plotMap : Areas : miniplot : deux options à supprimer 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#23]
deux options à supprimer dans le choix des miniPlot 

polar (area) et polar (radius) 

![optionsasupprimer](https://user-images.githubusercontent.com/22026724/35336109-a6694418-0117-11e8-9ef5-f3b5cc83460a.png)

**Comment by payementcha** [comment]
oui, et mettre le mini plot par défaut sur la carte

**Comment by jalazawa** [comment]
Fait
