### ISSUE TITLE
plotMap : delete : popup Link à supprimer 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#24]
Le select box pop up link est à enlever. 

![popuplinkaenlever](https://user-images.githubusercontent.com/22026724/35336276-1f8a9036-0118-11e8-974b-00945355affb.png)

**Comment by payementcha** [comment]
Oui et  imposer :
Color -> congestion
Width -> la taille du flux

**Comment by jalazawa** [comment]
Erreur pour l'instant l'initialisation se fait avec CONG. FEE et pas CONG. PROB + 

@demoulinflo est-ce que tu peux essayer le traitement addLoadFactorLink et me dire si on peut représenter la colonne congestion ? 

@demoulinflo est-ce que tu peux me confirmer qu'on laisse à disposition de l'utilisateur les autres variables dans Couleur et épaisseur ? comme Hurdle cost etc?

**Comment by jalazawa** [comment]
C'est fait et le choix de la mise à disposition des données sera fait plus tard.
