### ISSUE TITLE
plotMap : new : legende pour le parametre "color" 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#26]
Lorsque la valeur est nulle, on devrait avec une couleur "blanche" ou "vide" pour la variable au lieu d'une couleur moins prononcée. 

Exemple ici Lignite devrait être représenté par la couleur "blanche" si la valeur est nulle pour ce pays 

![valeur0](https://user-images.githubusercontent.com/22026724/35336520-f3c9fbde-0118-11e8-97ff-edbcb32843a7.png)

**Comment by payementcha** [comment]
oui

**Comment by bthieurmel** [comment]
Une première possibilité / proposition dans le comit ci-dessus. Questions / problèmes : 

- effectif uniquement sur les variables définies dans colors.csv (et donc pas les indicateurs min, max, ... par exemple)
- pas top avec des cas de valeurs négatives possibles (PSP ?)
- à intégrer à termes dans ``antaresViz`` ?

A rediscuter donc.

**Comment by payementcha** [comment]
Ok pour une couleur par variable dans le négatif. Ca sera plus claire. 
Pour avoir une solution intermédiaire, est-ce qu'on peut avoir des dégradés de rouges ?

**Comment by bthieurmel** [comment]
En fait je me suis mal exprimé. C'est dans tous les cas un dégradé qui s'affiche. Pour le moment de rouge à blanc pour toutes les variables en négatif.

**Comment by jalazawa** [comment]
C'est fait pour les variables positives. 

Pour l'instant, on ne peut pas tester avec les variables min, max sur le site. Je n'ai pas trouvé de variable négative. à discuter au prochain point.

**Comment by jalazawa** [comment]
Fait.
