### ISSUE TITLE
plotMap, prodStack et exchangeStack : changer le nom de la requête 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#27]
Changer le nom de la requête H5 

![requesteh5](https://user-images.githubusercontent.com/22026724/35336630-48b421ce-0119-11e8-95d2-c8503aa2a0d9.png)

Nouveau nom : DONNEES A IMPORTEES 

@payementcha tu confirmes le nom ?

**Comment by payementcha** [comment]
oui : 
"Données importées"

et un titre pour la section en dessous : 
"Données graphiques"

**Comment by bthieurmel** [comment]
Vous voulez quoi ? "Données" ne vous convient pas ? (Maintenant qu'on a mis "Tirage à importer" et "Tirage à visualiser")

**Comment by jalazawa** [comment]
La demande initiale date de 23 jours. Les modifications sont parfaites. Je clos.
