### ISSUE TITLE
plotMap : current Layout : charger un fond de carte déjà réalisée  

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#30]
Lors du démarrage de l'application bpNumerique2018, il faut pouvoir charger les 12 fichiers h5 comme indiqué ici #17. 

Il faut aussi pouvoir charger un fond de carte. 

![chargerunfonddecarte](https://user-images.githubusercontent.com/22026724/35337258-f4bf1892-011a-11e8-8a1e-025ca771f4f2.png)

**Comment by payementcha** [comment]
Je n'ai pas compris ici la modification

**Comment by jalazawa** [comment]
Fait
