### ISSUE TITLE
plotMap : delete : option : une option à supprimer 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#32]
L'option Areas -> show labels est à supprimer. 

@payementcha tu confirmes ? cf. images ? 

![showlabelsavirer](https://user-images.githubusercontent.com/22026724/35337535-c87d0202-011b-11e8-8f51-6f0f9304bb54.png)

**Comment by payementcha** [comment]
Oui, je les trouve pas super lisible. 
Je serai même d'avis de contraindre encore plus les paramètres de la carte avec notamment : 
- Links : Taille correspond au flux, couleur aux congestions
- Couleur : laisser au choix de l'utilisateur
- Dans size : ne pas laisser le choix, toujours mettre la même chose (Nucléaire, Gas, Charbon, Lignite, Wind, Solar, MIsc. DTG, Misc. NDG, H. ROR, H. STOR, Step, (on fera peut-être des groupes si on modifier le H5)
- Toujours afficher le miniplot avec deux options (bar et pie)
- Laisser Pop-up

**Comment by jalazawa** [comment]
Ok, c'est à supprimer pour les autres demandes. Je vais les noter dans d'autres tickets.

**Comment by jalazawa** [comment]
Fait
