### ISSUE TITLE
Help : on change le contenu 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#33]
L'aide n'est plus nécessaire. 

Les données seront déjà chargées et nettoyées. 

L'onglet "Help" doit être supprimé. 

![ongletasupprimer](https://user-images.githubusercontent.com/22026724/35337728-3e7dbd16-011c-11e8-95c8-0c5e7a1a23c9.png)

**Comment by payementcha** [comment]
On peut plutôt 
Le remplacer par une explication du contenu de chaque on onglet.
Ecrire un texte qui explique chaque onglet du coup. 
Et quelques référence vers les URL BP et OpenData

**Comment by jalazawa** [comment]
Finalement, on va changer le contenu. 

Ce sera un  RMarkdown.

**Comment by jalazawa** [comment]
Question simple : qui le fait ? 

```Le remplacer par une explication du contenu de chaque on onglet.
Ecrire un texte qui explique chaque onglet du coup.
Et quelques référence vers les URL BP et OpenData```

**Comment by demoulinflo** [comment]
Supprimer l'onglet "Aide" / A remplacer par l'onglet "A propos" (nouvel issue)

**Comment by bthieurmel** [comment]
Fait. Il faut maintenant du contenu...!

**Comment by demoulinflo** [comment]
Je ferme l'issue. Le traitement du contenu du "nouvel onglet" est traité dans l'issue #56.
