### ISSUE TITLE
renommer les colonnes des fichiers H5 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#34]
En fonction de #7 

Est-ce qu'on renomme les colonnes ou on crée de nouvelles colonnes ?

**Comment by payementcha** [comment]
Les deux : 
- Renommer les colonnes 
- Créer et supprimer des colonnes

**Comment by jalazawa** [comment]
Pour rajouter des colonnes qui sont des combinaisons linéaires dans le fichier H5 

Il faut utiliser addProcessingH5() du package antaresProcessing 


```R
addProcessingH5(opts = opts,  mcY = "mcInd",

               evalAreas = list(Tota = "`H. STOR` + `MISC. DTG`",
                                Tota2 = "`NODU` + `NP COST` + 1"),
               addExportAndImport = TRUE,
               addLoadFactorLink = TRUE,
               addNetLoad = TRUE,

```

**Comment by bthieurmel** [comment]
Pour appliquer un changement automatique des noms de colonnes en français dans l'ensemble des modules, pouvez-vous compléter et me ré-envoyer le fichier suivant ? (noeud + liens)

[columnNames_v2.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1695160/columnNames_v2.xlsx)

**Comment by payementcha** [comment]
Bonjour, 

Voici  la nouvelle liste. Tout ce qui est blanc doit disparaître. 
Pour les congestions il faudra qu'on fasse un calcul de colonne pour mutualiser congestion+ et congestion-.

A+

[columnNames_v3.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1695248/columnNames_v3.xlsx)

**Comment by bthieurmel** [comment]
Ok pour ne pas afficher les blancs dans les modules. 

Cependant, dans un soucis de mutualisation du travail fait sur le BP pour ``antaresViz`` en général, si on peux remplir l'ensemble des champs pour la traduction **fr**, cela serait top.

**Comment by payementcha** [comment]
Voici un fichier avec toutes les colonnes moins une. Je laisse la R&D confirmer le nom des colonnes.

**Comment by payementcha** [comment]
Bonjour, 

Je galère avec l'écriture du H5, je comprends pas bien son fonctionnement. 
Voici ce qu'on souhaite faire : 
 1- importer une étude
 2- removeVirtualAreas pour les "STEP" avec newCols=FALSE pour mettre tout en PSP
 3- removeVirtualAreas pour les "effacements courts" avec new Cols=TRUE pour avoir la production des effacements
 4- removeVirtualAreas pour les nœuds de production '"lu_X" et "X_rs"
 5- faire une combinaison linéaire entre la colonne "MISC. DTG" du area et la nouvelle colonnes effacements de l'étape 3
6 - faire une combinaison linaire avec cong prob + et cong prob - pour avoir un indicateur 0/1 sur la congestion
7- écrire le H5

On arrive pas bien à comprendre comment faire cet enchaînement avec les fonctions addProcessing, writeAntaresH5 et removeVirtualAreas.

Une idée ?

**Comment by jalazawa** [comment]
Quelques remarques 

- "area" : dans l'application j'ai constaté que c'était traduit par "zone" et dans le fichier excel par "noeud" 
@demoulinflo choix final ? 
- MIX. FUEL a été traduit par "thermique_autre" pour moi ce serait plutôt "thermique_mixte" @demoulinflo qu'est que tu en penses ?  

- "FLOW QUAD." : erreur de frappe : fluxç_quadratique --> flux_quadratique
- "UCAP LIN.", @fredbreant j'ai traduit ça par "flux_absolu", c'est correct ? 

- impossibilité de récupérer le travail pour ```antaresViz``` , exemple MISC. DTG pour le BP c'est effacements mais dans le cas général c'est "thermique autre". Est-ce qu'on veut forcément avoir l'application en français et en anglais pour d'autre utilisateur que le bp numérique ? 

[columnNames_v5.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1719963/columnNames_v5.xlsx)

**Comment by jalazawa** [comment]
Après avoir discuté avec @fredbreant j'ai rajouté une troisième colonne ```Français``` pour antaresViz. 

Pour l'application, il faudra utiliser la colonne BP. 

[columnNames_v6.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1720315/columnNames_v6.xlsx)

**Comment by demoulinflo** [comment]
• "area" : pas d'avis, on peut rester sur nœud  
• "MIX. FUEL" : ok pour "thermique_mixte" (fichier mis à jour)
•"FLOW QUAD." : erreur de frappe : fluxç_quadratique --> flux_quadratique ok (fichier mis à jour)

Dans l'idée, se rapprocher au plus près de ce qui est fait pour AntaresViz me paraît bien.

**Comment by jalazawa** [comment]
Merci, on peut passer à l’implémentation.

**Comment by bthieurmel** [comment]
Fait pour le module plot & map

**Comment by jalazawa** [comment]
D'après le fichier Area(s) doit être traduit pas nœud(s)

On fait référence à Areas et Links dans la légende de la carte. 

cf. image 

![nom_application_carte_legende](https://user-images.githubusercontent.com/22026724/36437260-cacc5f16-1666-11e8-9c28-08146ea3ce06.png)


On fait référence à Zone dans la selection de donnée pour la carte à deux endroits 

cf. image 

![nom_application](https://user-images.githubusercontent.com/22026724/36436976-085d166e-1666-11e8-898a-e037d1ebb36c.png)

pareil pour les 3 autres modules, on doit utiliser soit noeud ou noeuds dans la sélection de donnée. 

![nom_application_carte](https://user-images.githubusercontent.com/22026724/36437180-969c8fb8-1666-11e8-859c-c1a2bdd2f487.png)

![nom_application_echanges](https://user-images.githubusercontent.com/22026724/36437184-984799a2-1666-11e8-873c-ad8aeef0b8f1.png)

![nom_application_production](https://user-images.githubusercontent.com/22026724/36437185-9939a3d2-1666-11e8-870c-21b022167531.png)

sinon, c'est ok pour moi

**Comment by bthieurmel** [comment]
Corrigé.

**Comment by jalazawa** [comment]
Parfait.
