### ISSUE TITLE
application : new : rajouter le logo RTE 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#35]
@payementcha as-tu une préférence sur le logo ? 

Tu peux choisir l'image et la rajouter ici ? 

https://www.google.fr/search?biw=1680&bih=835&tbm=isch&sa=1&ei=EptoWp46yuNT5-CHgAc&q=rte+france&oq=rte+france&gs_l=psy-ab.3..0j0i24k1l9.5470.6671.0.6747.7.7.0.0.0.0.78.410.7.7.0....0...1c.1.64.psy-ab..0.7.408...0i67k1j0i30k1j0i8i30k1.0.ycWoX5ZFBdQ

**Comment by payementcha** [comment]
![rte_logo_seul_rvb](https://user-images.githubusercontent.com/23703085/35347037-d61c80f8-012b-11e8-8851-19e86f1b9770.jpg)

Depuis la charte graphique de RTE

**Comment by jalazawa** [comment]
cf. #36 pour l'emplacement

**Comment by jalazawa** [comment]
Fait
