### ISSUE TITLE
Application : changer le bandeau noir en rouge 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#36]
Changer le bandeau de l'application 

![bandeau_rouge_bp](https://user-images.githubusercontent.com/22026724/35338215-98c92eee-011d-11e8-9df4-039c5ebd53e0.png)

Changer le bandeau en rouge comme pour le bp. 

cf. lien 

http://www.rte-france.com/sites/default/files/bp2017_synthese_17.pdf

**Comment by payementcha** [comment]
oui

et remplacer AntaresViz par BP2017
Le logo RTE à droite ce serait bien.

**Comment by jalazawa** [comment]
Fait
