### ISSUE TITLE
exchangesStack : traduire les paramètres en Français 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#40]
changer le nom de ces paramètres 

![parameters](https://user-images.githubusercontent.com/22026724/35338981-9ac62f74-011f-11e8-8587-f262ae2cd5c7.png)

@payementcha as-tu une proposition ?

**Comment by payementcha** [comment]
timeStep -> pas de temps
mcYear -> tirage
area -> pays
dateRange -> date
unit -> unité
legend -> légende
stepPlot -> à supprimer
drawPoints -> à supprimer
title -> titre

**Comment by jalazawa** [comment]
C'est intentionnel ou tu as oublié un des arguments mcYear? 

Premier mcYear --> tirage à importer 
Deuxième mcYear --> tirage à visualiser 

pour dateRange, je te propose plutôt **période** 

@payementcha ça te vas ? 

Est-ce qu'on garde les augments title dans les différents graph ?

**Comment by jalazawa** [comment]
Fait.
