### ISSUE TITLE
plotMap : traduction : traduire les paramètres 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#41]
changer le nom des paramètres 

![parameters](https://user-images.githubusercontent.com/22026724/35339155-2069778a-0120-11e8-9206-6ef4d990cdba.png)

@payementcha as-tu une proposition ?

**Comment by payementcha** [comment]
mcYear -> tirage
By time id -> par heure
daterange -> date
areas -> pays
color -> couleur
size -> taille (faute de mieux)
popup -> mini-graph
label -> informations

**Comment by jalazawa** [comment]
nouvelle proposition 

mcYear -> tirage
By time id -> par heure
daterange -> date
areas -> pays
color -> couleur
size -> **variable a representer dans le mini-graph**
miniplot -> **mini-graph**
areaChartType -> **type de mini-graph**
bar chart -> **diagramme baton**
pie chart -> **camembert**
popup -> **variable a représenter dans la fenêtre surgissante** 
show labels -> **representer les valeurs** 

@payementcha ça te vas ? 
Question : Est-ce que les paramètres doivent commencer par une majuscule ? 


@payementcha tu peux le faire pour links, s'il te plait ? désolé pour le niveau de détail demandé...

**Comment by bthieurmel** [comment]
@jalazawa & @payementcha : attention aux noms trop long du genre "**variable a representer dans le mini-graph**", ça va pas passer / être tronqué dans l'interface. Il faut rester sur des noms courts.

**Comment by payementcha** [comment]
Je suis d'accord pour les noms courts, cf mon commentaire précédent.
Pas de soucis pour le niveau de détail et pour links :
- Color -> Couleur
- Width -> Epaisseur
- PopUp -> à supprimer

**Comment by jalazawa** [comment]
OK
