### ISSUE TITLE
prodStack : legende : Bionegery -> Autre renouvelable

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#42]
@payementcha peux-tu préciser la demande ? 

à traiter en même temps que #8 et #6

**Comment by payementcha** [comment]
Pour les changements de noms de colonnes du fichiers, j'avais préparé le fichier de conversion suivant :+1: 

[columnNames.xlsx](https://github.com/rte-antares-rpackage/bpNumerique2018/files/1660312/columnNames.xlsx)

Pour la légende du prodstack, qui me semble indépendante des noms de colonnes : 
Changer l'appellation bioénergie en autre renouvelable

**Comment by jalazawa** [comment]
OK traduction de 

bioenergie == **autre renouvelable**

**Comment by jalazawa** [comment]
C'est fait
