### ISSUE TITLE
Menu "Hypothèses" - Sélection du scénario 

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#46]
La sélection du scénario est une fonction "commune" permettant de conditionner les données à afficher dans les onglets "Prod", "Conso" et "Intercos"
--> Ajouter une liste déroulante permettant de sélectionner le scénario (idéalement au-dessus des onglets)
-------> Valeurs : "Ampère", "Hertz", "Volt" et "Watt"
-------> La correspondance entre les hypothèses EnR (bas, moyen, haut) / thermiques et les scénarios sont disponibles dans le fichier joint 
[Scenario_correspondance_th_enr.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1695963/Scenario_correspondance_th_enr.xlsx)
--> Supprimer les listes déroulantes "ENR" et "thermiques" de l'onglet "Production"
-------> La liste déroulante "zones" reste dans l'onglet "Production"

**Comment by bthieurmel** [comment]
Ci-dessous les valeurs présentes dans les données et affichées dans le graphiques de production : 

``
 "biogas"       "biomass"      "geothermal"   "hydro"        "hydrokinetic" "other"        "solar"        "waste"       
 "wave"         "wind"         "gaz"          "charbon"      "nucléaire"    "effacement"   "lignite"      "autre"       
"fioul" 
``

Pouvez-vous mettre à jour le fichier *Scenario_correspondance* pour bien retrouver effectivement ces valeurs ? Je peux trouver certaines corresponances, mais je ne veux pas faire de bétises....!
(onshore & offshore = wind, pv = solar, .... enrEU ?)

**Comment by demoulinflo** [comment]
Après avoir rebouclé avec Charles, pour compléter les données fournies par Charles, il semblerait qu'il ne manque que la correspondance entre les scénarios et les "trajectoires" des filières "enr", "thermal" et "nuclear" définies dans les données déjà fournies. 
La table de correspondance est disponible ci-dessous : 
[Correspondance_scenarios_enr_th.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1699437/Correspondance_scenarios_enr_th.xlsx)

A disposition si ce n'est pas clair...
Si besoin je peux faire évoluer le tableau fourni par Charles pour que toutes les données soient associées directement à un scénario (ampere, hertz, volt ou watt) sans passer par la table de correspondance.
