### ISSUE TITLE
Menu "Hypothèses" - Onglet "Interconnexions" - Contenu

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#47]
Les données à afficher sont disponibles dans le fichier joint : 
[Links.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1696024/Links.xlsx)

Les données dépendent du scénario sélectionné (cf. issue #45 + table de correspondance).
La colonne "hypothesis" identifie le scénario EnR (bas, médian, haut).

2 graphiques sont à afficher : 
--> "Evolution des capacités d'import en hiver"
-------> season = "winter", type = "HP", from = {"be", "ch", "de", "es", "it", "gb", "ie"}, to = "fr" 
--> "Evolution des capacités d'export en hiver"
-------> season = "winter", type = "HP", from = "fr", to = {"be", "ch", "de", "es", "it", "gb", "ie"}

Les données doivent être affichées pour chaque année, de 2017 à 2036, distinguant les capacités par frontière comme dans l'exemple ci-dessous.
![ex_graph_intercos](https://user-images.githubusercontent.com/23702978/35818264-76cc912c-0a97-11e8-8152-b3d94b361391.png)

**Comment by bthieurmel** [comment]
Je prend donc l'enr affecté à la france dans ce tableau : 

````
Pays;filiere1;Ampère;Hertz;Volt;Watt
France;enr;haut;moyen;moyen;haut
Europe;enr;haut;haut;moyen;haut
France;nuclear;ampere;hertz;volt;watt
Europe;nuclear;base;base;base;base
France;thermal;ampere;hertz;volt;watt
Europe;thermal;base;base;base;base
````
ou devons-nous faire également une distinction fr / europe ?

**Comment by demoulinflo** [comment]
Il faut distinguer France / Europe en fonction de la zone sélectionnée

![2018-02-09_10h25_11](https://user-images.githubusercontent.com/23702978/36020631-49aca0e2-0d7b-11e8-81d9-3876b496800b.png)

**Comment by demoulinflo** [comment]
Pour tracer nos échanges...
La table de correspondance est mise à jour avec l'ajout de la correspondance intercos.

**Comment by jalazawa** [comment]
Est-ce qu'on peut clôture cette première demande sur les hypothèses d'interco ? @demoulinflo 

J'ai l'impression que le travail a été fait.

**Comment by demoulinflo** [comment]
Oui. Je ferme.
