### ISSUE TITLE
Menu "Synthèse" - Navigation et contenu

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#48]
**Navigation**

La page du menu "Synthèse" doit présenter un menu de navigation latéral à gauche.
![layout_menu_navigation](https://user-images.githubusercontent.com/23702978/35916622-e89c25a8-0c02-11e8-8618-d1f462772dc3.png)

Les items du menu sont les suivants.
- Les scénarios _(item sélectionné par défaut)_
- Ampère
       - Principe _(item sélectionné par défaut si l’item « Ampère » est sélectionné)_
       - Hypothèses principales
       - Résultats
- Hertz
       - Principe _(item sélectionné par défaut si l’item « Hertz » est sélectionné)_
       - Hypothèses principales
       - Résultats
- Volt
       - Principe _(item sélectionné par défaut si l’item « Volt » est sélectionné)_
       - Hypothèses principales
       - Résultats
- Watt
       - Principe _(item sélectionné par défaut si l’item « Watt » est sélectionné)_
       - Hypothèses principales
       - Résultats

**Comment by demoulinflo** [comment]
Sous quel format peut-on vous envoyer le contenu des pages ? RMarkdown ?

**Comment by bthieurmel** [comment]
Oui. Soit directement en rmarkdown, soit en word et je ferai la conversion.

**Comment by demoulinflo** [comment]
Pour faire suite à nos derniers échanges concernant l'ergonomie de cet onglet et aux premiers "retours" externes, il faudrait supprimer cet onglet.
Les "données" sur les scénarios seront intégrées au menu  "Hypothèses".
