### ISSUE TITLE
Hypothèses de production : traduction

### ISSUE THREAD

**Issue by bthieurmel** [rte-antares-rpackage/bpN#50]
````
enr       biogas 
enr      biomass 
enr   geothermal
enr        hydro
enr hydrokinetic
enr        other
enr        solar
enr        waste 
enr         wave 
enr         wind 
````

Pouvez-vous me donner vos traductions pour les hypothèses de production enr ?

wind -> éolien
solar -> solaire
autre -> autre renouvelables
biogas  -> 
biomass  -> 
geothermal -> 
hydro -> 
hydrokinetic -> 
waste  -> 
wave  ->

**Comment by payementcha** [comment]
wind -> éolien
 solar -> solaire
 autre -> autres renouvelables
 biogas -> biogaz
 biomass -> biomasse
 geothermal -> géothermie
 hydro -> hydraulique
 hydrokinetic -> hydrolien
 waste -> déchets
 wave -> vagues

**Comment by jalazawa** [comment]
Pour wave je propose houlomotrice, qu'est que tu en penses @fredbreant ?  

https://fr.wikipedia.org/wiki/%C3%89nergie_marine

**Comment by fredbreant** [comment]
Je suis gêné car je pense que par wave, ils entendent marée et pas vague.
J'aurais donc plutôt envie de mettre "marémotrice" dans la traduction plutôt que "houlomotrice" même si "houlomotrice" est la traduction la plus littérale.

**Comment by jalazawa** [comment]
@demoulinflo tu confirmes "houlomotrice" ?

**Comment by demoulinflo** [comment]
Je confirme "houlomotrice" (l'usine "marémotrice" de la Rance est prise en compte dans la part fil de l'eau hydro).

**Comment by jalazawa** [comment]
Au final 

wind -> éolien
solar -> solaire
autre -> autres renouvelables
biogas -> biogaz
biomass -> biomasse
geothermal -> géothermie
hydro -> hydraulique
hydrokinetic -> hydrolien
waste -> déchets
wave -> houlomotrice

**Comment by bthieurmel** [comment]
Fait.

**Comment by jalazawa** [comment]
OK
