### ISSUE TITLE
Echanges : bug : comparaison : le paramètre stepPlot n'est plus actif 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#53]
Lorsque je compare deux années, l'option stepPlot n'est plus active. 

![bug_compare](https://user-images.githubusercontent.com/22026724/36152125-1ced0716-10ca-11e8-935a-a8135fc5c5e3.png)

**Comment by bthieurmel** [comment]
Ouais, pas mal de petit soucis encore avec les différentes possibilités / combinaisons de ``manipulateWidget`` (comme #61). Je vais regarder ça... (et donc ne te presse pas pour pusher ``manipulateWidget``)

**Comment by bthieurmel** [comment]
En fait c'était dû au partage des inputs entre les modules. J'ai pour le moment tout désactivé. A voir une fois que l'ensemble des paramètres / données seront figés ce que l'on fait. (Si on partage ou pas).

**Comment by jalazawa** [comment]
OK
