### ISSUE TITLE
Menu "A propos"

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#56]
Création d'un menu "à propos" contenant  : 
> un lien vers la page de téléchargement du Bilan prévisionnel
> un topo sur Antares

@fredbreant : Peux-tu faire une proposition de contenu ?

**Comment by bthieurmel** [comment]
Première version en ligne. A ce propos, pensez-vous envisageable d'avoir un peu de "pub" pour datastorm du genre "powered par datastorm" en bas de la page ? Avec également pourquoi pas des informations sur les packages / librairies utilisées et développées par la R&D de RTE ?

Qui ne demande rien n'a rien......;

**Comment by demoulinflo** [comment]
Comme vu par mail, je vous laisse la main sur cet onglet !

**Comment by jalazawa** [comment]
Il faut intégrer les modifs de @fredbreant

**Comment by bthieurmel** [comment]
Fait

**Comment by jalazawa** [comment]
Merci
