### ISSUE TITLE
application : charte pour les couleurs 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#57]
Il faut prendre en compte ces couleurs 

[couleur.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1723114/couleur.xlsx)

Pour la consommation : 
-	Fixer les couleurs uniquement pour le graphique par secteurs et random les autres niveaux (même si j’ai tout mis dans le fichier)

**Comment by bthieurmel** [comment]
Intégré. Cependant, il me manquait des catégories pour la production. Ci-joint le fichier utilisé. Je vous laisse valider/modifier.


[couleur_prod.zip](https://github.com/rte-antares-rpackage/bpN/files/1724335/couleur_prod.zip)

**Comment by jalazawa** [comment]
ça me vas. Je me dé-assigne.

**Comment by jalazawa** [comment]
Fait.
