### ISSUE TITLE
ProdStack : new : permettre de représenter les flexibilités dans Other ou un autre type 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#6]
Les flexibilités ne sont pas représentées dans l'empilement eco2mix de base. 

Il faut soit les représenter dans other soit dans flex. 

Il faut modifier l'alias eco2mix, sa légende etc. en passant notamment par ce fichier 

https://github.com/rte-antares-rpackage/bpNumerique2018/blob/master/inst/GraphicalCharter.csv

![reduire_epaisseur_des_lignes](https://user-images.githubusercontent.com/22026724/35329137-0369d718-00ff-11e8-9a3e-4b1e2de41105.png)

**Comment by payementcha** [comment]
Avec l'utilisation de la fonction RemoveVirtualAreas
- le pompage-turbinage sera dans PSP
- les effacements auront une autre colonnes dédiées ? ou seront dans la catégorie MISC. DTG ?
Dans l'idéal il y aurait une autre production dédiée aux effacements comme le nucléaire, le gaz ou autre

**Comment by jalazawa** [comment]
L'alias a été modifié.
