### ISSUE TITLE
Couleur pour les variable _std, _ min, _max 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#60]
Je propose de garder la même couleur entre 

VAR, VAR_std, VAR_min et VAR_max

@demoulinflo qu'est que tu en penses ? 

Actuellement pour l'éolien 

wind_min (brun)

![wind_min](https://user-images.githubusercontent.com/22026724/36209104-18d474f8-119b-11e8-90dd-0349bd7d3288.png)

wind (bleu)

![wind](https://user-images.githubusercontent.com/22026724/36209110-1de6cd24-119b-11e8-9a48-fddb4555c113.png)

**Comment by demoulinflo** [comment]
Ok pour une même couleur !

**Comment by bthieurmel** [comment]
Fait

**Comment by jalazawa** [comment]
OK
