### ISSUE TITLE
plotMap : non respect de la charte graphique lors de l'initialisation du graphique 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#61]
Lorsqu'on visualise pour la première fois la carte, la charte graphique n'est pas respectée (load en violet au lieu de brun) 

cf. images 

AVANT (initialisation) 

![load_init_plotmap](https://user-images.githubusercontent.com/22026724/36210818-bcbce524-119f-11e8-98aa-eeeed2593985.png)

Après avoir basculer sur une autre variable puis enfin sur Load 

![load_init_plotmap_2](https://user-images.githubusercontent.com/22026724/36210835-c7d48a48-119f-11e8-9ce6-0f0835af30b9.png)

**Comment by bthieurmel** [comment]
Corrigé

**Comment by jalazawa** [comment]
Yes
