### ISSUE TITLE
Menu "Resultats" - Production - Mise à jour

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#63]
Le texte à afficher est mis à jour dans le fichier RMarkdown joint.

Le paramétrage par défaut du graphique doit être modifié comme ci-dessous (spécifications en cours de mise à jour).

Données / pas de temps	X : Horaire
Données / tirage	           : 2 tirages (1 ; 2)  
Tirage	                           : 1
Période                               : Du 15/01 au 21/01
Zone	                           : fr 

[resultats_production.zip](https://github.com/rte-antares-rpackage/bpN/files/1724576/resultats_production.zip)

**Comment by bthieurmel** [comment]
Fait
