### ISSUE TITLE
détail : ils existent deux onglets production dans cette petite application 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#64]
Est-ce qu'on change le nom de ces deux onglets pour plus de lisibilité ? ou non ? 

cf.  images 

1 
![production_hypotheses](https://user-images.githubusercontent.com/22026724/36212535-7756e62e-11a4-11e8-897e-52059559d278.png)

2 
![production_empilement](https://user-images.githubusercontent.com/22026724/36212541-78fc507c-11a4-11e8-942c-a6efd83e186e.png)

**Comment by demoulinflo** [comment]
Yes, et ce ne sera pas le seul changement (je n'ai pas les idées très claires encore)...
Pour ne pas se perdre, dans un premier temps on peut changer le nom du menu "Hypothèses" / "Production" par "Hypothèses"/"Parc de production"
