### ISSUE TITLE
Menu "Hypothèses" - Nouvel onglet "CO2"

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#66]
Ajouter un onglet CO2 contenant l'évolution un graphique présentant l'évolution des émissions de CO2 en France.
Les données à afficher sont les données historiques de 2012 à 2016 et les données du scénario pour les coupes 2025, 2030, 2035.

Titre du graphique : Évolution des émissions de CO2 en France
Type de graphique : Histogramme (dans l'esprit des graphiques du BP, cf. exemple ci-dessous)

Les données sont fournies dans le fichier joint.

Un texte d'accompagnement (par scénario) sera fourni ultérieurement.

[co2.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1724845/co2.xlsx)

![graph_co2_extrait_bp](https://user-images.githubusercontent.com/23702978/36216068-aa0c153e-11a5-11e8-9c50-ab16ce4567c1.png)

**Comment by bthieurmel** [comment]
Rajouté. En attendant la suite donc.

**Comment by demoulinflo** [comment]
Ci-joint le contenu à afficher (identique pour tous les scénarios).

[hypotheses_co2.zip](https://github.com/rte-antares-rpackage/bpN/files/1725103/hypotheses_co2.zip)

**Comment by demoulinflo** [comment]
Au niveau mise en forme, du graphique il faut uniquement 2 couleurs, une pour les données historiques (gris hachuré ou gris clair si hachures non gérées) et une pour les données 2025 / 2030 / 2035.

@bthieurmel : On peut définir une largeur max du graph, en pixel ou en pourcentage ? Le but étant qu'il ne prenne pas toutes la largeur de la page, le rendu n'est pas terrible avec si peu de données !

**Comment by bthieurmel** [comment]
Fait. Je te laisse regarder.

**Comment by demoulinflo** [comment]
C'est top ! 
Pour être au plus proche de ce qui est affiché dans le BP, possible de colorer pleinement les barres "scénario" en gris (comme dans l'image fournie dans le premier post) ?

**Comment by demoulinflo** [comment]
Il faudrait aussi supprimer la valeur affichée dans la barre (l'affichage au survol suffit).

**Comment by bthieurmel** [comment]
J'ai supprimé la valeur. Pour la coloration pleine, je ne suis pas sûr que cela soit possible..... à voir quand j'aurais du temps en trop...!

**Comment by demoulinflo** [comment]
Pas de soucis ! Et aucune urgence, on est vraiment dans le fine tuning ;)

Si la coloration pleine n'est pas possible, il faudrait juste inverser les motifs, l'idée étant que les données "scénarios" ressortent plus que les données "historiques".

**Comment by bthieurmel** [comment]
Je viens de faire l'inversion.
