### ISSUE TITLE
Menu "Hypothèses" - Onglet "Bilans"

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#68]
Ajouter un onglet "Bilans" (après "Parc de production") présentant les mix de production aux horizons 2025, 2030, 2035.

Titre du graphique : Bilans énergétiques
Type de graphiques : Cf. extrait du BP ci-dessous
![bilans_energetiques_ampere](https://user-images.githubusercontent.com/23702978/36218038-0760f1aa-11ab-11e8-9004-181dac3a65c9.png)

Les données sont disponibles pour le scénario hertz dans le fichier joint pour test.
Je mettrai à jour les données pour les autre scénarios ensuite.

[bilans_energetiques.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1725008/bilans_energetiques.xlsx)

**Comment by bthieurmel** [comment]
En fait, c'est pas un ``sunburst``, qui est un graphique hiérarchique, mais un ``double donut``... Je regarde ce que je peux faire.

**Comment by bthieurmel** [comment]
Bon, je viens de vous mettre une ça en ligne. Pour la légende, je suis obligé de coller une image. Vous pouvez m'en envoyer une en meilleure résolution éventuellement.

**Comment by demoulinflo** [comment]
Ci-dessous la légende en meilleur résolution.
![img_legende_bilans_energetiques](https://user-images.githubusercontent.com/23702978/36323042-877ff0fa-1347-11e8-80ee-ec0f6fee2e4c.png)

Aure problème graphique, les "légendes" CO2 / part d'eNR / part de nucléaire ne sont pas alignées avec les bilans... Possible d'ajuster l'alignement ? Sinon à supprimer.

**Comment by bthieurmel** [comment]
MAJ.

**Comment by demoulinflo** [comment]
Ci-joint les bilans énergétiques pour les 4 scénarios : 
[bilans_energetiques.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1737189/bilans_energetiques.xlsx)

**Comment by bthieurmel** [comment]
Fait.

**Comment by demoulinflo** [comment]
Les infobulles sont tronquées par la légende sur le bilan 2025. Est-il possible de faire quelque chose ?
![bp_num_bilans_infobulle_tronquee](https://user-images.githubusercontent.com/23702978/36386600-29b225d0-158e-11e8-8dba-84939beaffbc.png)

**Comment by bthieurmel** [comment]
J'ai réduit un peu la taille des graphiques du coup...

**Comment by demoulinflo** [comment]
Pas de soucis, c'est bien comme ça.
