### ISSUE TITLE
Menu "Hypothèses" - Interconnexions - Ajout du texte et ajustements graphiques

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#69]
Les données doivent être affichées pour les années 2016, 2022, 2025, 2030 et 2035 uniquement.

Le texte à ajouter est joint dans le fichier RMarkdown (texte identique pour tous les scénarios).

[hypotheses_interconnexions.zip](https://github.com/rte-antares-rpackage/bpN/files/1725194/hypotheses_interconnexions.zip)

@bthieurmel : Même question que pour les graphes CO2, est-il possible de limiter la largeur des graphes pour qu'il ne prennent pas toute la page ?

**Comment by bthieurmel** [comment]
Fait. A valider.

**Comment by demoulinflo** [comment]
Parfait pour les graphes.

Pour le texte, légères modifications pour l'affichage de la liste.
J'ai ajouté des "puces" dans le RMarkdown ci-dessous.

[hypotheses_interconnexions.zip](https://github.com/rte-antares-rpackage/bpN/files/1727091/hypotheses_interconnexions.zip)

**Comment by bthieurmel** [comment]
Fait.

**Comment by demoulinflo** [comment]
Presque, il manque les ";" à la fin des 2 premières puces

**Comment by bthieurmel** [comment]
Rajouté.

**Comment by demoulinflo** [comment]
OK pour moi.
