### ISSUE TITLE
application : donnée H5 : writeAntaresH5 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#7]
Pour l'instant, on ne peut pas modifier facilement la structure et les données stockées dans le fichier H5. 

Exemple d'opération non dispo pour l'instant : Rajouter des colonnes qui ne soient pas des combinaison linéaire, changer le structure, changer les dates. changer le nom des colonnes etc. 

Pour le problème de nom de colonne : on peut rajouter des colonnes avec le nom français --> C'est OK maintenant @payementcha  ça te vas ? 
Pour les combinaisons linéaires, c'est possible aussi. 

Au lieu de lire les données, de les nettoyer (appel à removeVirtualAres) et de les écrire enfin, il serait intéressant de pouvoir donner à la fonction un antaresDataList. Cet objet serait modifier par l'utilisateur avant écriture et respecterait une certaine structure.

**Comment by payementcha** [comment]
Il me semble toujours intéressant de pouvoir modifier comme on le souhaite le H5 avant de l'écrire.
Sinon pour les besoins court terme : 
- Modifier les noms de colonnes
- Supprimer des colonnes
- Faire des combinaisons linéaires entre colonnes

Si c'est déjà bon, je suis preneur de la méthode

A+

Charles

**Comment by jalazawa** [comment]
Dernier update, il y'a 18 jours. 

Est-ce que ce besoin est toujours d'actualité ? est-ce que l'écriture des fichiers posent encore problème ? 

des news ?

**Comment by demoulinflo** [comment]
Pas de problème de mon côté, on peut fermer l'issue
