### ISSUE TITLE
Menu "Hypothèses" - Consommation - Ajout du texte et mise à jour des données

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#71]
Le texte à ajouter est disponible de le fichier joint : 
[hypotheses_consommation.zip](https://github.com/rte-antares-rpackage/bpN/files/1727783/hypotheses_consommation.zip)

En complément, le titre du graphique doit être modifié en "Evolution de la consommation".

Les données doivent être mises à jour à partir du fichier transmis par mail en parallèle.

**Comment by bthieurmel** [comment]
Fait

**Comment by demoulinflo** [comment]
Il faudrait également supprimer l'année 2036.

Pascal regarde pour définir un ordre d'affichage plus pertinent.

@bthieurmel : Charles t'avait fourni une charte pour les couleurs ? Si oui pourrais-tu me l'envoyer?

**Comment by bthieurmel** [comment]
Couleur ici #57

**Comment by demoulinflo** [comment]
L'**ordre des empilements** doit être le suivant (si facilement paramétrable, sinon on abandonne)

Pour les secteurs, de haut en bas : 
Pertes
Transport, agriculture et énergie
Résidentiel
Tertiaire
Industrie

Pour les usages, de haut en bas : 
Pertes
VE & VHR
Chauffage
Eau chaude sanitaire
Climatisation & ventilation
Eclairage intérieur
Cuisson
Froid
Lavage
Produits gris & bruns résidentiels
Autres usages résidentiels
Bureautique et autres usages tertiaires
Autres usages

**Comment by demoulinflo** [comment]
J'ai mis à jour le fichier des couleurs avec les usages définis par Pascal.
Pour prise en compte. 
[couleurs.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1728793/couleurs.xlsx)

**Comment by bthieurmel** [comment]
Update ok
