### ISSUE TITLE
Menu "hypothèses" - Parc de production - Correction des données

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#73]
Il y a un premier problème liés aux capacités hydrauliques fournies (hydro/hydro et hydro/step).

En creusant l'analyse, il s'avère également que la table de correspondance actuelle ne suffit pas, les trajectoires hydro et step n'étant pas les mêmes que les trajectoires pour les autres EnR.

J'envoie par mail les fichiers corrigés.

Si le fonctionnement actuel via le fichier de correspondance devient trop compliqué, pas de soucis pour changer le format (supprimer la table de correspondance et passer par un fichier unique...)
A dispo pour en discuter.

**Comment by bthieurmel** [comment]
Fait. A checker et valider.

**Comment by demoulinflo** [comment]
Nouvelle correction dans les données.
Je fais suivre par mail le fichier corrigé.

**Comment by bthieurmel** [comment]
Update. Format du graphique également changé...

**Comment by demoulinflo** [comment]
Très bien. merci.
