### ISSUE TITLE
DATA : LIMIT RAM : limiter le nombre d'année importées à 2 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#74]
On doit limiter le nombre de tirage à importer à deux dans tous les modules. 

![mcyear_importees](https://user-images.githubusercontent.com/22026724/36298957-08658e20-12fb-11e8-850f-d50dbf50e49e.png)

**Comment by bthieurmel** [comment]
Fait. Le plus simple : 

existe en shiny avec le ``selectizeInput`` en passant des ``options`` : 

https://github.com/selectize/selectize.js/blob/master/docs/usage.md

Je les donc implémenter dans ``manipulateWidget`` et modifié les modules.

**Comment by jalazawa** [comment]
Merci.
