### ISSUE TITLE
Lisibilité : rajouter le tirage "moyen" dans la liste des tirages 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#75]
Actuellement, un utilisateur récupère le tirage moyen s'il n'importe aucun autre tirage. 

Ce n'est pas le fonctionnement optimal. 

Il faut rajouter dans la liste le tirage "moyen". 

Actuellement, voici la liste proposée 

![tirage_moyen](https://user-images.githubusercontent.com/22026724/36299050-6fe50a30-12fb-11e8-970f-d8ea6f9a8289.png)

**Comment by bthieurmel** [comment]
Même réponse que #74

**Comment by jalazawa** [comment]
Ok pour moi
