### ISSUE TITLE
Menu "Résultats/Hypothèses" - Interconnexions - Graphiques

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#76]
Supprimer l'affichage en pourcentage (peu d'intérêt).

**Comment by demoulinflo** [comment]
Une remarque pertinente qui vient de m'être remontée.
Il est important  d'avoir la même échelle en ordonnée sur les 2 graphiques export / import (on peut la fixer à 35000).

**Comment by bthieurmel** [comment]
Fait
