### ISSUE TITLE
Menu "Résultats/Hypothèses" - Parc de prod - Affichage en pourcentages

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#77]
L'affichage en pourcentages en très pertinent dans cet onglet.
En revanche, il faudrait que, la légende (MW) et les valeurs affichées sur le graphe (capacité installée par filière) changent (%)... Ce n'est pas clair pour l'utilisateur sinon.

Si possible, on fait a modification. Sinon on supprime cet affichage.

Même remarque pour la consommation.

**Comment by bthieurmel** [comment]
Fait. Le label de l'axe des y ainsi que les valeurs affichées dans la légende changent. Les valeurs affichées sur le graphiques contiennent de façon permanente les deux infos.

**Comment by demoulinflo** [comment]
Ca me parait pas mal ! 
On reste là-dessus en attendant les retours "utilisateurs".

**Comment by demoulinflo** [comment]
Bug

Si on sélectionne pourcentage et qu'on change de scénario, "Pourcentage" reste sélectionné dans la liste déroulante alors que ce sont les valeurs qui sont affichées.

il faudrait idéalement laisser l'affichage en pourcentage (ou a minima réinitialiser la valeur sélectionnée à "Valeur")

**Comment by bthieurmel** [comment]
Corrigé.
