### ISSUE TITLE
application : détail : changement de nom dans l'application 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#78]
Pour plus de lisibilité pour les nouveaux utilisateurs, je ferais bien deux changements 

Etude --> Choisissez une (ou des) étude(s) 

![nom_etudes](https://user-images.githubusercontent.com/22026724/36367308-6466355e-1552-11e8-8b20-807713c5ae27.png)

Scénario --> Choisissez un des quatre scénarios

![nom_scenarios](https://user-images.githubusercontent.com/22026724/36367365-a5af7ed0-1552-11e8-90b7-e83e5b489aa7.png)
 
@demoulinflo qu'est que tu en penses ?

**Comment by demoulinflo** [comment]
C'est surtout intéressant pour les études pour montrer qu'on peut en sélectionner plusieurs..
Pour alléger un peu je dirais : 
- Scénario ->Scénario sélectionné
- Etude  -> Etude(s) sélectionnées 

Pendant qu'on est dans le détail, il faudrait également : 
- Dans le menu "Hypothèses/résultats",  mettre "Scénario sélectionné" et la liste déroulante sur la même ligne
- Dans le menu "Analyse détaillée"
--- utiliser la même police de caractère / taille que pour "scénario sélectionné". Il faudrait également le même alignement à gauche. Idem pour le texte affiché si aucune étude n'est sélectionnée (police de caractère/ taille et alignement à gauche).

**Comment by bthieurmel** [comment]
OK.
