### ISSUE TITLE
ProdStack : legende : rajouter dans la légende la défaillance et le déversement 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#8]
Comme #6 

Il faut modifier la légende. 

La défaillance c'est UNSP. ENRG

@payementcha avec quelle couleur ? 

Le déversement SPIL. ENRG 

une couleur pour le déversement @payementcha ?

**Comment by payementcha** [comment]
La défaillance est à ajouter à la production. Proposition de couleur 
![legendeempilement](https://user-images.githubusercontent.com/23703085/35344251-945854fa-0124-11e8-8bcd-88b088815f46.png)
RGB (219,169,169).
Le déversement à la consommation et doit donc avoir le même traitement que les exports. Couleur RGB (252,216,185)
Je vous insère les couleurs de la légende complète.
![legendeempilement](https://user-images.githubusercontent.com/23703085/35344265-a1a207aa-0124-11e8-8e3d-63a24d583adb.png)

**Comment by jalazawa** [comment]
OK quand je regarde ta légende, tu as aussi Export, Import (dans notre empilement ils sont combinés). 

Est-ce que tu veux les rajouter ? 

Tu as aussi des catégories comme Marine ?

**Comment by payementcha** [comment]
si on peut les ajouter on le fait, sinon pas du tout prioritaire
Pour limiter les données on va fusionner bioénergies et marine dans autre renouvelable et tout ça correspond à la colonne MISC. NDG

**Comment by jalazawa** [comment]
C'est noté, pour l'instant ce qui est fait dans le graphique c'est bioenergies = MISC. NDG

**Comment by bthieurmel** [comment]
alias implémenté actuellement : 

````
# change eco2mix alias
setProdStackAlias(
  name = "eco2mix",
  variables = alist(
    "Pompage/turbinage" = PSP,
    "Import/export" = -(BALANCE + `ROW BAL.`),
    "Autre renouvelable" = `MISC. NDG`,
    "Eolien" = WIND,
    "Solaire" = SOLAR,
    "Nucléaire" = NUCLEAR,
    "Hydraulique" = `H. ROR` + `H. STOR`,
    "Gaz" = GAS,
    "Charbon" = COAL,
    "Lignite" = LIGNITE,
    "Fioul" = OIL,
    "Défaillance" = `UNSP. ENRG`,
    "Déversement" = `SPIL. ENRG`,
    "Effacement" = `MISC. DTG` + `MIX. FUEL`
  ),
  colors = c("#1147B9", "#969696", "#166A57", "#74CDB9", "#F27406", "#F5B300", "#2772B2", "#F30A0A", "#AC8C35", 
             "#B4822B", "#8356A2", "#DBA9A9",  "#FCD8B9", "#ADFF2F"),
  lines = alist(
    "Consommation" = LOAD + `SPIL. ENRG`,
    "Production" = NUCLEAR + LIGNITE + COAL + GAS + OIL + `MIX. FUEL` + `MISC. DTG` + WIND + SOLAR + `H. ROR` + `H. STOR` + `MISC. NDG` + pmax(0, PSP) + `UNSP. ENRG`
  ),
  lineColors = c("#875627", "#EB9BA6"),
  lineWidth = 2
)

setProdStackAlias(
  name = "thermalFirst",
  variables = alist(
    "Pompage/turbinage" = PSP,
    "import/export" = -(BALANCE + `ROW BAL.`),
    "Nucléaire" = NUCLEAR,
    "Lignite" = LIGNITE,
    "Charbon" = COAL,
    "Gaz" = GAS,
    "Fioul" = OIL,
    "Autre thermique" = `MIX. FUEL`,
    "Effacement" = `MISC. DTG`,
    "Autre renouvelable" = `MISC. NDG`,
    "Eolien" = WIND,
    "Solaire" = SOLAR,
    "Hydraulique fil" = `H. ROR`,
    "Hydraulique lac" = `H. STOR`
  ),
  colors = c("#1147B9", "#969696", "#F5B300", "#B4822B", "#AC8C35", "#F30A0A", "#8356A2", "#7F549C", "#ADFF2F", "#166A57", "#74CDB9", "#F27406", "#3D607D", "#5497D0")
)
````

A valider / finaliser, notamment avec les données finales (#6, #42)

**Comment by payementcha** [comment]
Ok pour moi pour la partie Eco2mix. 
Pour la partie thermalFirst, on laisse tomber.

**Comment by jalazawa** [comment]
J'ai une question pour valider le besoin 

Les effacements se trouvent dans deux colonnes dans les résultats ANTARES pour tous les pays ? 

"Effacement" = `MISC. DTG` + `MIX. FUEL`

MISC. DTG dans les nœuds virtuels ? et MIX FUEL dans le nœud réel ?

**Comment by demoulinflo** [comment]
Hum non...
> Les effacements  c'est MISC. DTG (uniquement) 
> Actuellement la catégorie MIX. FUEL n'est pas utilisée... Elle pourrait l'être et ce ne serait pas des effacements. Pour avoir quelques chose de propre, il faudrait ajouter une catégorie "Autre" = MIX. FUEL avec la couleur noir (par exemple) et retirer MIX. FUEL des effacements

**Comment by jalazawa** [comment]
C'est un peu bizarre que @payementcha  valide l'alias avec la partie effacement un peu sensible.. mais bon ok

Au final, on doit rajouter cette catégorie 

thermique_autre = MIX FUEL 

avec cette couleur #000000

Si vous avez besoin de jouer avec les couleurs alors vous pouvez utiliser ce site 

https://www.rapidtables.com/convert/color/rgb-to-hex.html

et donc au final pour l'alias eco2mix on a 

```R
setProdStackAlias(
  name = "eco2mix",
  variables = alist(
    "Pompage/turbinage" = PSP,
    "Import/export" = -(BALANCE + `ROW BAL.`),
    "Autre renouvelable" = `MISC. NDG`,
    "Eolien" = WIND,
    "Solaire" = SOLAR,
    "Nucléaire" = NUCLEAR,
    "Hydraulique" = `H. ROR` + `H. STOR`,
    "Gaz" = GAS,
    "Charbon" = COAL,
    "Lignite" = LIGNITE,
    "Fioul" = OIL,
    "Défaillance" = `UNSP. ENRG`,
    "Déversement" = `SPIL. ENRG`,
    "Effacement" = `MISC. DTG`
    "thermique autre" =  `MIX. FUEL`
  ),
  colors = c("#1147B9", "#969696", "#166A57", "#74CDB9", "#F27406", "#F5B300", "#2772B2", "#F30A0A", "#AC8C35", 
             "#B4822B", "#8356A2", "#DBA9A9",  "#FCD8B9", "#ADFF2F", "#000000"),
  lines = alist(
    "Consommation" = LOAD + `SPIL. ENRG`,
    "Production" = NUCLEAR + LIGNITE + COAL + GAS + OIL + `MIX. FUEL` + `MISC. DTG` + WIND + SOLAR + `H. ROR` + `H. STOR` + `MISC. NDG` + pmax(0, PSP) + `UNSP. ENRG`
  ),
  lineColors = c("#875627", "#EB9BA6"),
  lineWidth = 2
)

```

Ce n'est pas encore totalement clair pour moi, j'ai quelques questions. 

D'après le besoin de Charles 

```
La défaillance est à ajouter à la production. Proposition de couleur RGB (219,169,169).
Le déversement à la consommation et doit donc avoir le même traitement que les exports. Couleur RGB (252,216,185)
```
 Benoit a fait les modifications demandées mais : 

1- Etes-vous sur de vouloir rajouter le déversement dans la courbe de consommation @demoulinflo  ? 

dans la code ça se traduit comme ça 
- "Consommation" = LOAD + `SPIL. ENRG`
dans le graphique c'est la courbe brun 

Si c'est confirmer il faudrait rajouter quelques lignes pour l'expliquer à l'utilisateur 

2- Est-ce que vous voulez rajouter les effacements à la courbe de production @demoulinflo ? 

dans le code ça se traduit comme ça 
"Production" = ..... `MISC. DTG` .... 

Il faudrait expliquer à l'utilisateur quelles sont les quantités prises en compte par la courbe (thermique, effacement, turbinage des step etc.).

3- Est-ce que vous voulez rajouter dans la courbe consommation la partie pompage des step ? 
@demoulinflo 

````"Consommation" = LOAD + `SPIL. ENRG` + pmax(0,-PSP) ````

La partie turbinage est prise en compte dans la production via ```pmax(0, PSP)```

**Comment by demoulinflo** [comment]
Il faut se rapprocher au maximum de la présentation du Bilan prévisionnel.

Les modifications principales :  
-> Supprimer la courbe "production"
-> Mettre uniquement la "LOAD" dans la courbe "Consommation"
-> Supprimer la catégorie "Lignite"
-> Distinguer pompage et turbinage
-----> Pompage = - pmax(0, -PSP)
-----> Turbinage = pmax(0, PSP)
-> Distinguer export et import (les formules ci-dessous me semblent ok...)
-----> Import = pmax(0, -(BALANCE + `ROW BAL.`))
-----> Export = - pmax(0, (BALANCE + `ROW BAL`))
-> Modifier l'ordre d'empilement (cf. spécifications)
-> Afficher le déversement en négatif
-----> Déversement = - `SPIL. ENRG`

Le détail est rappelé dans les spécifications.

**Comment by demoulinflo** [comment]
En complément, est-il possible d'afficher "GW" en unité pour le pas horaire et "GWh" pour les autres pas de temps ?

**Comment by bthieurmel** [comment]
Je viens de le mettre en place, à savoir : 

````
tmp_var <- alist(
  "Déversement" = -(`SPIL. ENRG`),
  "Export" = - pmax(0, (BALANCE + `ROW BAL.`)),
  "Pompage STEP" = - pmax(0, -PSP),
  "Nucléaire" = NUCLEAR,
  "Charbon" = COAL,
  "Autre renouvelable" = `MISC. NDG`,
  "Gaz" = GAS,
  "Hydraulique" = `H. ROR` + `H. STOR`,
  "Turbinage STEP" = pmax(0, PSP),
  "Fioul" = OIL,
  "Import" = pmax(0, -(BALANCE + `ROW BAL.`)),
  "Eolien" = WIND,
  "Solaire" = SOLAR,
  "Effacements" = `MISC. DTG`,
  "Défaillance" = `UNSP. ENRG`
)
````

C'est ok pour vous ? (Consommation pas toujours au dessus de l'ensemble, ordre différent des graphiques illustratifs mis dans les spéc, ....) ?

**Comment by demoulinflo** [comment]
J'ai checké avec une semaine type du BP, c'est pas mal !
Premières remarques : 
-> dans l'ordre d'empilement, les exports doivent être en dessus du pompage des steps (conformément aux spécifications V0.1). Du coup ce doit être le problème également pour le déversement (liste inversée pour les catégories négatives ?).
-> il faudrait décaler la catégorie "autre renouvelable" au dessus de la catégorie gaz pour que le gaz apparaisse "en bande" -> je mets à jour ce point dans les specs V0.2

Je continue les vérifications...

**Comment by bthieurmel** [comment]
Je viens de MAJ l'ordre

**Comment by demoulinflo** [comment]
Ca parait bien, à checker avec de la défaillance et du déversement, je cherche les bonnes semaines !

**Comment by demoulinflo** [comment]
Déversement ça semble bon aussi

**Comment by demoulinflo** [comment]
Par contre quand on a de la défaillance il y a un petit écart entre les courbes... 

![defaillance](https://user-images.githubusercontent.com/23702978/37042558-935d30a0-2156-11e8-9e94-5943baea0624.png)

Après première analyse rapide, il semblerait que ca vienne des effacements courts non pris en compte, je regarde plus en détail le script de génération des H5

**Comment by demoulinflo** [comment]
J'ai utilisé le script suivant : 

# Ecriture du fichier H5 avec suppression des "virtual areas"
writeAntaresH5(overwrite = TRUE, 
                 removeVirtualAreas = TRUE, 
                 timeSteps = c("hourly", "daily", "weekly","monthly", "annual"),
                 storageFlexibility = list(c("pump_w", "pump_d", "turb_w", "turb_d"), c("ie_dsr_4h", "ni_dsr_4h", "gb_dsr_4h", "de_dsr_4h", "fr_dsr_4h"), NULL),
                 production = list(NULL, NULL, c("lu_be", "lu_de", "es_rs", "gb_rs", "de_rs", "be_rs")),
                 reassignCosts = list(FALSE, TRUE, TRUE), 
                 newCols = list(FALSE, TRUE, FALSE))

Quand je lis le résultat du H5 (readAntares(timeStep = "hourly", mcYears = 210, areas = c("fr"))), je n vois pas la colonne "fr_dsr_4h"...

Si j'ai compris le fonctionnement du script, elle devrait être ajoutée non ?

**Comment by bthieurmel** [comment]
Pour les nouvelles colonnes, il faut obligatoirement lister explicitement l'ensemble des colonnes que l'on souhaite avec l'argument ``select`` (pas ultra pratique....) : 

````
readAntares(opts = opts_h5, timeStep = "hourly", mcYears = 1, 
                  select = c("OP. COST", "MRG. PRICE", "CO2 EMIS.", "BALANCE", "MISC. NDG", "LOAD", "H. ROR",
  "WIND", "SOLAR", "NUCLEAR" , "LIGNITE", "COAL", "GAS", "OIL", "MIX. FUEL", "MISC. DTG", "H. STOR",
  "UNSP. ENRG", "SPIL. ENRG", "LOLD", "FLOW LIN.", "deversement", "congestion", "effacement", "fr_dsr_4h"))
````

Mais sinon, tout va bien, elles sont là et on peut s'en servir !

**Comment by demoulinflo** [comment]
Merci, j'ai retrouvé ma colonne :) 

Je teste le fonctionnement du addProcessing !

**Comment by demoulinflo** [comment]
Alors, on a 2 problèmes : 
--> il faut prendre en compte la variable recalculée "effacement" dans le prodstack (erreur de ma part dans les specs...)
--> mais le traitement AddProcessing génère des NA dans la colonne effacement

  # addProcessing repart du H5 pour faire les combinaisons linéaires
  # a faire pour tous les pas de temps
  for(ts in c("hourly", "daily", "weekly", "monthly", "annual")){
    addProcessingH5(mcY = c("mcInd", "mcAll"),
                    timeStep = ts,
                    evalAreas = list(effacement = "`MISC. DTG` + `ie_dsr_4h` + `ni_dsr_4h` + `gb_dsr_4h` + `de_dsr_4h` + `fr_dsr_4h`"),
                    evalLinks = list(congestion = "(`CONG. PROB +` + `CONG. PROB -`)/100"))
  }

**Comment by demoulinflo** [comment]
Comme tous les H5 sont générés, on peut sinon directement implémenter la formule au niveau du prodstack ?

"Effacements" = `MISC. DTG` + `fr_dsr_4h` + `ie_dsr_4h` + ...

**Comment by bthieurmel** [comment]
L'effacement initialement calculé n'est pas bon ? (avec uniquement fr_dsr_4h)

Si non, on peut effectivement le recalculer directement dans le prodstack, ou refaire un appel à addProcessing, au choix.

**Comment by demoulinflo** [comment]
Je viens de vérifier sur le H5 en cours de génération, le champ effacement est bien calculé.
Du coup au choix, soit on utilise la variable calculée "effacement", soit on applique la formule directe dans le prodstack.
Ce qui te paraît le plus propre/maintenable... Je mettrai à jour les specs en conséquence !

**Comment by bthieurmel** [comment]
Alors, dans l'ordre : 

- les NA étaient dû à un bug dans ``addProcessingH5``. Pour des générations futures, il faudra donc réinstaller la version de dev

``devtools::install_github("rte-antares-rpackage/antaresProcessing", ref ="develop", dependencies = F)``

- ``addProcessingH5`` fait le travail pour les mcInd **OU** les mcAll et non les deux. Il manque donc les nouvelles colonnes dans le tirage moyen. Le bon code de génération doit donc être pour des nouveaux fichiers : 

````
for(ts in c("hourly", "daily", "weekly", "monthly", "annual")){ 
  addProcessingH5(mcY = "mcAll",
                  timeStep = ts,
                  evalAreas = list(effacement = "`MISC. DTG` + `fr_dsr_4h`"),
                  evalLinks = list(congestion = "(`CONG. PROB +` + `CONG. PROB -`)/100"))
  
  addProcessingH5(mcY = "mcInd",
                  timeStep = ts,
                  evalAreas = list(effacement = "`MISC. DTG` + `fr_dsr_4h`"),
                  evalLinks = list(congestion = "(`CONG. PROB +` + `CONG. PROB -`)/100"))
  
}​
````

J'ai MAJ les fichiers dans l'application.

**Comment by bthieurmel** [comment]
Et je viens de MAJ l'application avec la bonne prise en compte de l'effacement.

**Comment by demoulinflo** [comment]
Du coup pour l'effacement tu es parti de la colonne calculée ou non ?
En fonction je laisserai (ou non) le calcul de la colonne dans le script de génération du H5... Et je vais tracer ce point dans les spécifications !

**Comment by demoulinflo** [comment]
Et il faudrait m'envoyer la version du package corrigé par mail !

**Comment by jalazawa** [comment]
Edit pour prendre en compte correctement ROW BAL. 

````
  "Export" = - pmax(0, BALANCE + pmax(0, -`ROW BAL.`)),

  "Import" = pmax(0, - (BALANCE) + pmax(0, `ROW BAL.`)),
  
)
````

**Comment by demoulinflo** [comment]
Merci Jalal. j'ai mis à jour les spécifications avec ces données.

**Comment by bthieurmel** [comment]
Export/Import update, package envoyé par mail.

Et je pars bien de la colonne calculée avec addProcessingH5. cf nouveau code ci-dessus
