### ISSUE TITLE
Menu "Analyse détaillée", onglet "Production" - Titre des graphiques avec nom de l'étude

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#80]
Il faut rappeler le titre de l'étude dans le titre du graphique.
En effet, en cas de sélection multiple, il faut pouvoir identifier à quelle étude se réfère les graphiques...

Pour alléger le titre, on peut supprimer le libellé "Production".

Le pattern peut être le suivant : 
<nom_etude> (zone <zone>, tirage <mc_year>)

**Comment by bthieurmel** [comment]
Fait

**Comment by demoulinflo** [comment]
Modification suite à la décision d'affichage des données France uniquement : 

> Sélection simple    
>>> Titre actuel : Production <zone> (tirage <num_tirage>)   
>>> Nouveau titre : Tirage <num_tirage>      
> Sélection multiple  
>>> Titre actuel : <nom etude> : <zone> (tirage <num_tirage>)
>>> Nouveau titre : <nom etude> : Tirage <num_tirage>   

Je crée une issue indépendante pour la zone "France" uniquement

**Comment by bthieurmel** [comment]
Fait

**Comment by demoulinflo** [comment]
Ok pour les onglets "Production" et "Echanges"

Pour l'onglet "Chroniques", appliquer les mêmes titres (le nom des variables est visible en ordonnées, c'est suffisant pour le moment)

Pour l'onglet "Cartes", si c'est possible d'avoir un titre sur la carte, idem... Sinon pas de titre !

Pour le tirage "moyen", actuellement le titre est "Tirage average", est-il possible de le modifier en "Tirage moyen" ? (et remplacer "moyenne" par "moyen" dans la liste déroulante) 

L'affichage de ce tirage moyen n'est d'ailleurs pas évident/intuitif... à réfléchir...

**Comment by bthieurmel** [comment]
C'est fait. Pas possible pour la carte.

**Comment by demoulinflo** [comment]
Ok, on reste comme ça !
