### ISSUE TITLE
Menu "Analyse détaillée" - Ajout d'axes de comparaison - Simplification

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#81]
Suite à nos échanges, je pense qu'on peut laisser l'ajout d'axes de comparaison en cas de sélection simple et multiple.

Afin de simplifier néanmoins le fonctionnement, je propose de supprimer la liste déroulante permettant de choisir les paramètres à comparer.
Si la case à cocher est sélectionnée, on considère que les paramètres "zone" et "tirage" peuvent varier indépendamment.

En fonction des décisions prises cette semaine (affichage France only ou Europe), on pourra adapter le libellé de la case à cocher au mieux.

Ci-joint le texte à mettre à jour si aucune étude n'est sélectionnée. 
[analyse_detaillee.zip](https://github.com/rte-antares-rpackage/bpN/files/1739491/analyse_detaillee.zip)

**Comment by bthieurmel** [comment]
Fait.
