### ISSUE TITLE
Affichage de la carte / zoom

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#82]
Est-il possible de zoomer et centrer sur l'Europe à l'affichage de la carte ?
Si faisable facilement uniquement...

**Comment by bthieurmel** [comment]
Le niveau affiché prend en compte l'ensemble de la carte. Le zoom suivant n'arrive pas à avoir toute l'europe... (il manque un bout en haut ou en bas....!).

Pour centrer, à voir ce que je peux faire (c'est dû je pense aux areas virtuels et/ou autres liens pas affichés....)

**Comment by jalazawa** [comment]
@bthieurmel si le problème vient des noueds virtuelles et des liens virtuelles alors il faut changer l'emplacement de ces noeuds dans le fichier RDS ou lorsqu'on utilise la fonction mapLayout. 

Je pense que si on met tous les nœuds virtuels en mer du nord ou en méditerranée entre la Corse et France, il n'y aura plus de problème de centrage...

**Comment by bthieurmel** [comment]
![image](https://user-images.githubusercontent.com/8750326/36528700-4496340c-17b6-11e8-82d9-55b271c94052.png)

C'est pas le layout le soucis à priori. Je vais regarder un peu le code....

**Comment by bthieurmel** [comment]
Je viens de rajouter une initialisation des limites de la carte par rapport au layout.

**Comment by jalazawa** [comment]
Merci et merci leaflet.

**Comment by demoulinflo** [comment]
C'est vraiment pas mal comme ça !
