### ISSUE TITLE
Menu "Analyse détaillée" - Année de l'output Antares vs. Année de l'étude

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#83]
Les dates affichées sur les graphiques correspondent aux dates de l'output Antares.
Actuellement, toutes les simulations sont effectuées sur la base du calendrier 2028-2029.

Les résultats présentés correspondant aux coupes 2025, 2030 et 2035, ce n'est pas intuitif de sélectionner des dates en 2028-2029...

Une idée de solution ? 

Dans le pire des cas on expliquera le principe dans le texte mais ça risque de faire réagir pas mal de monde...

**Comment by bthieurmel** [comment]
C'est pas le top mais j'ai déjà passé les dates en français, et supprimé l'affichage de l'année dans les deux boxes....

**Comment by demoulinflo** [comment]
C'est un bon compromis je pense, je vais essayer de vendre ça comme ça ! 
J'ajouterai un texte explicatif pour l'année 28-29 (calendrier unique pour comparaison, ...).
