### ISSUE TITLE
Affichage des données France 

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#84]
Affichage des données France (sauf pour la carte)

- Résultats et hypothèses / Parc de production : Supprimer la liste déroulante "pays" ("fr" par défaut) 
- Analyse détaillée / Production : Masquer la liste déroulante "nœud" ("fr" par défaut)
- Analyse détaillée / Echanges : Masquer la liste déroulante "nœud" ("fr" par défaut)
- Analyse détaillée / Chroniques : 
-- Quand "table = noeud" : La liste déroulante "élément" doit contenir la valeur "fr" 
-- Quand "table = liens" : La liste déroulante "élément" doit contenir les liens de et vers "fr"

**Comment by bthieurmel** [comment]
Fait
