### ISSUE TITLE
Ajout du scénario Ohm

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#85]
Ajout du scénario Ohm (en fin de liste)

Le contenu de l'onglet "Généralités" est joint ci-dessous.
[hypotheses_generalites.zip](https://github.com/rte-antares-rpackage/bpN/files/1748895/hypotheses_generalites.zip)

Autres données en cours de préparation...

**Comment by demoulinflo** [comment]
Nouveau fichier "correspondance" et "hypothèses parc prod" contenant les données pour Ohm envoyés par mail.

**Comment by demoulinflo** [comment]
Nouveau fichier "bilan" contenant les données pour Ohm dispo ci-dessous.
[bilans_energetiques_V2.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1749130/bilans_energetiques_V2.xlsx)

Pour tous les scénarios : 
-- La catégorie "Charbon" a été ajoutée (nécessaire pour Ohm)
-- La catégorie "Energies marines" a été ajoutée (auparavant intégrée à tort dans les bioénergies)

Le code couleur de la catégorie "énergies marines" est ajouté dans le fichier "couleurs" ci-dessous : 
[couleurs.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1749137/couleurs.xlsx)

La légende ne convient plus, je regarde pour la mettre à jour !

**Comment by bthieurmel** [comment]
En attente des fichiers "correspondance" et "hypothèses parc prod" -> PJ manquantes dans le mail !

**Comment by demoulinflo** [comment]
PJ envoyées par mail... Dsl pour le petit loupé ;)

**Comment by bthieurmel** [comment]
Il manquera également les données de CO2

**Comment by demoulinflo** [comment]
Voilà !
[co2_V2.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1778795/co2_V2.xlsx)

**Comment by bthieurmel** [comment]
OK
