### ISSUE TITLE
Résultats et hypothèses - Maj. onglet "Parc de production"

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#87]
- Ajouter les données 2016 
- Modifier agrégation/catégories en utilisant la colonne "filiere_BP_num" 
- Mettre à jour les couleurs 
- Modifier le contenu texte avec le nouveau fichier fourni
- Afficher les données en GW, avec 1 décimale

Les fichiers mis à jour sont joints par mail complémentaire.

**Comment by demoulinflo** [comment]
Il y a un petit soucis au niveau de l'affichage des énergies renouvelables, les capacités affichées prennent en compte plusieurs trajectoires (haut et moyen pour ampere (au lieu de haut), pas testé les autres...)

**Comment by bthieurmel** [comment]
Normalement corrigé.

**Comment by demoulinflo** [comment]
Ok pour les filières solaire et éolien.
Le problème persiste pour les filières hydro (hydro et step).

**Comment by bthieurmel** [comment]
En effet. C'est bon a priori.

**Comment by demoulinflo** [comment]
C'est tout bon, merci !
