### ISSUE TITLE
Tab Data : Tab Analysis : delete : retirer le check box mcYear on all modules ?

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#9]
Retirer le check box  : mcYear on all modules ?

![compare](https://user-images.githubusercontent.com/22026724/35333166-0807d46e-010e-11e8-8a13-1fc01c0bc854.png)

**Comment by payementcha** [comment]
oui

**Comment by jalazawa** [comment]
Fait
