### ISSUE TITLE
Résultats et hypothèses - Maj. onglet "Bilans"

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#90]
- Mettre à jour le contenu texte avec le nouveau contenu fourni ci-dessous.
- Mettre à jour les couleurs avec le fichier "couleurs V2" fourni

[hypotheses_bilans.zip](https://github.com/rte-antares-rpackage/bpN/files/1779934/hypotheses_bilans.zip)

**Comment by demoulinflo** [comment]
La légende est incorrecte (couleurs KO + catégorie "énergies marines" manquante).
Je regarde pour la mettre à jour.

**Comment by demoulinflo** [comment]
La légende est incorrecte. Je la mets à jour.

**Comment by demoulinflo** [comment]
Nouvelle légende dispo ci-dessous (incluse dans le fichier "couleurs V2" également).
Si besoin de la modifier (taille, ...), je peux la mettre à jour.

![hypotheses_resultats_bilans_legende](https://user-images.githubusercontent.com/23702978/36964118-8c8e42aa-204d-11e8-8c4a-eb1c587f60cd.png)

[couleurs_V2.xlsx](https://github.com/rte-antares-rpackage/bpN/files/1780022/couleurs_V2.xlsx)

**Comment by demoulinflo** [comment]
Le premier point de l'issue n'a pas pris en compte, pour rappel ci-dessous : 

- Mettre à jour le contenu texte avec le nouveau contenu fourni ci-dessous.
- Mettre à jour les couleurs avec le fichier "couleurs V2" fourni

[hypotheses_bilans.zip](https://github.com/rte-antares-rpackage/bpN/files/1779934/hypotheses_bilans.zip)

**Comment by bthieurmel** [comment]
Je l'avais pas vu...

**Comment by demoulinflo** [comment]
Héhé, pas de soucis ;)
