### ISSUE TITLE
Analyse détaillée - Caractérisation des tirages dispos - Questions

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#93]
Le choix des tirages à afficher va être fait en fonction de "semaine type" permettant d'identifier des phénomènes divers (semaine hiver avec/sans, défaillance, déversement, ...)

Chaque phénomène pourra donc être visualisé en sélectionnant le tirage qui convient, et la semaine ciblée.

Afin de faciliter la visualisation, est-il possible de : 
- Initialiser par défaut une semaine définie en fonction du tirage sélectionné ?
- Définir des "noms" à la place des numéros de tirage ?
Concrètement, l'utilisateur sélectionnerait par exemple un tirage libellé "hiver sans vent" et l'affichage serait initialisé directement sur la semaine présentant cette caractéristique.

J'ai déjà caractérisé quelques semaines nous permettant de tester ce fonctionnement s'il est possible de le mettre en place (dès que j'aurai générer les H5 bien sur...)

Si ce n'est pas possible, les combinaisons type seront expliquées en mode "texte", mais ce sera beaucoup moins intuitif...

Dispo pour en parler !

**Comment by bthieurmel** [comment]
Cela doit être faisable....

**Comment by demoulinflo** [comment]
Ok, top, on regarde ça dès que j'ai généré les H5 !

**Comment by demoulinflo** [comment]
On peut faire le test ?

Tirage 35 -> "Hiver - Peu de vent"
Semaine par défaut -> Du 5 février au 11 février

**Comment by demoulinflo** [comment]
Ci-dessous le paramétrage provisoire pour les 8 années (maj. dans spécifications V0.2)

**Libellé du tirage ; Numéro du tirage ; Période**
Vague de froid ; 760 ; Du 08/01 au 14/01
Hiver Vent +    ; 210 ; Du 01/01 au 07/01	
Hiver Vent -     ; 35	 ; Du 05/02 au 11/02	
Eté                   ;  1	 ; Du 10/07 au 16/07
Tirage 2	        ; 2	 ; Du 01/01 au 07/01	
Tirage 3	        ; 3	 ; Du 01/01 au 07/01	
Tirage 4	        ; 4	 ; Du 01/01 au 07/01	
Tirage 5	        ; 5	 ; Du 01/01 au 07/01

**Comment by bthieurmel** [comment]
Fait. Format du fichier utilisé : 

````
Label;mcYear;date_start;date_end
Vague de froid;760;2029-01-08;2029-01-14
Hiver Vent +;210;2029-01-01;2029-01-07
Hiver Vent -;35;2029-02-05;2029-02-11
Eté;1;2028-07-10;2028-07-16
Tirage 2;2;2029-01-01;2029-01-07
Tirage 3;3;2029-01-01;2029-01-07
Tirage 4;4;2029-01-01;2029-01-07
Tirage 5;5;2029-01-01;2029-01-07
````

Questions : 

- on garde cette initialisation pour les cartes ou on reste sur l'année ?
- MAJ des titres en conséquences ? ("Tirage Vague de froid" ou "Vague de froid") ?

**Comment by demoulinflo** [comment]
Ca marche bien ! 
Il serait en effet mieux d'harmoniser avec la carte, c'est plus clair pour l'utilisateur.

En revanche, j'ai montré le fonctionnement à Charles et il a eu une idée qui me paraît beaucoup plus pertinente (même si cela implique de revenir (un peu) en arrière..) !
-> On garde les numéros des tirages "classiques"
-> On ajoute une liste déroulante qui présente le phénomène à visualiser (Vague de froid, hiver vent +, ...)
-> La sélection entraine l'initialisation des champs "pas de temps", "tirage" et "période" 

Ca me semble beaucoup plus clair comme fonctionnement .... 

Je n'ai pas eu le temps d'y réfléchir plus en détail, si cela vous semble pertinent, go !

**Comment by bthieurmel** [comment]
Mis la solution discutée

**Comment by jalazawa** [comment]
@payementcha et @demoulinflo est-ce que vous pouvez valider le comportement ? 

pour moi c'est OK mais je me pose des questions sur les scénarios. 

Est-ce que l'équipe BP peut valider les données et les regarder attentivement ?

Par exemple, est-ce que c'est normal d'importer avec le scénario "Hiver vent +" et d'exporter avec le scénario "Hiver vent -" ? 
 

Merci

**Comment by demoulinflo** [comment]
C'est mieux, mais pas encore top au niveau ergonomie (je l'ai fait tester à quelques personnes et ce n'est pas encore concluant...). J'y réfléchis et je vous fais une proposition !

Je vais checker les données également !

**Comment by demoulinflo** [comment]
Il faut bien distinguer l'idée d' "évènement" (= combinaison {tirage, période}) du paramétrage du graphique.

Est-il possible de complètement "sortir" la sélection de l'évènement du graphe (cf. maquette ci-dessous) ?
La sélection de l'événement entraîne la réinitialisation des paramètres du graphique + l'actualisation.

A dispo pour en parler.

![maquette_choix_evenement](https://user-images.githubusercontent.com/23702978/37604903-ed33d7a4-2b89-11e8-8bff-90dd73dcf40d.png)


Dans les faits, cela permettra à l'utilisateur de visualiser différents évènement sans passer par la zone de paramétrage un peu plus complexe.

**Comment by bthieurmel** [comment]
Non, ce n'est pas possible.... Le plus simple est de discuter de cela par téléphone.

**Comment by demoulinflo** [comment]
Ok, je t'appelle en sortant de réunion !

**Comment by demoulinflo** [comment]
Nouvelle caractérisation à prendre en compte : 

Label;mcYear;date_start;date_end
Hiver moyen;35;2029-01-08;2029-01-14
Hiver avec vent fort;1;2029-01-29;2029-02-04
Hiver avec vent faible;35;2029-02-05;2029-02-11
Vague de froid;760;2029-01-08;2029-01-14
Eté moyen;4;2028-07-10;2028-07-16

Les tirages 2, 3, 5 et 210 ne sont plus affichés.
-> Je mettrai à jour les H5 une fois ces tirages définitivement validés.

Les tirages doivent être affichés dans l'ordre ci-dessus.

Le tirage "Hiver moyen" est sélectionné par défaut.

**Comment by bthieurmel** [comment]
On avait parlé d'un seul événement possible (au maximum) par mcYear, ce qui n'est pas le cas ici (deux pour l'année 35). Et j'avoue que cela pose des soucis avec le code....

Pouvons-nous donc respecter cela et MAJ le tableau en conséquence ?

**Comment by demoulinflo** [comment]
Ok, j'ai modifié l'évènement "hiver avec vent faible"

Label;mcYear;date_start;date_end
 Hiver moyen;35;2029-01-08;2029-01-14
 Hiver avec vent fort;1;2029-01-29;2029-02-04
 **Hiver avec vent faible;5;2029-02-26;2029-03-04**
 Vague de froid;760;2029-01-08;2029-01-14
 Eté moyen;4;2028-07-10;2028-07-16

**Comment by bthieurmel** [comment]
C'est ok.
