### ISSUE TITLE
Hypothèses et resultats - Nouvel onglet "Variantes"

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#94]
Ajouter un nouvel onglet après l'onglet "Généralités".
Comme l'onglet "Généralités", le contenu de cet onglet varie selon le scénario sélectionné. 
Le contenu par scénario est fourni ci-dessous.

[hypotheses_bingo.zip](https://github.com/rte-antares-rpackage/bpN/files/1784887/hypotheses_bingo.zip)

**Comment by bthieurmel** [comment]
Fait.

**Comment by demoulinflo** [comment]
Tu peux fixer une largeur max à l'image ? La résolution n'est pas top sur grand écran.

Je n'avais pas ce problème avec le .Rmd, la taille max correspondait à la taille du .jpeg original ...

**Comment by bthieurmel** [comment]
J'ai remis l'image dans sa taille originale. Après cela dépendra aussi du zoom du navigateur...

**Comment by demoulinflo** [comment]
yep c'est bien comme ça !
merci !
