### ISSUE TITLE
Analyse détaillée - Affichage multiple - Bug

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#95]
Petit soucis... Le changement de paramétrage est pris en compte sur Ampère uniquement ! 

![bug_prodstack_multi](https://user-images.githubusercontent.com/23702978/37086019-711a0c6e-21ee-11e8-97f3-e7fde46c592d.png)

Pour reproduire : 
--> charger 3 scénarios (pas reproduit avec 2 scénarios)
--> changer une première le paramétrage -> KO, appliquer au premier scénario uniquement

**Comment by demoulinflo** [comment]
Il y a quand même un petit soucis pour 2 scnéarios également. J'ai du cliquer 2 fois sur le bouton de rafraichissement..

A traiter avec la modification du fonctionnement des tirages à importer / visualiser (j'ouvre l'issue de rapidement)

**Comment by bthieurmel** [comment]
J'arrive pas à reproduire. Chez moi c'est ok...

**Comment by demoulinflo** [comment]
Ok
Je laisse ouvert jusqu'au test de l'issue #96, on verra à ce moment là

**Comment by jalazawa** [comment]
J'ai reproduit le bug sur internet Explorer mais pas sur Firefox et Chrome. 

On savait déjà qu'il pouvait exister des différences entre internet Explorer, Firefox, Chrome et Edge.  

La partie javaScript d'internetExplorer a toujours du retard par rapport aux autres. 

@demoulinflo tu veux qu'on rajoute un petit mot dans le "a propos" ? 

Je pense que régler les petits problèmes uniquement pour la version IE11 n'est pas la bonne solution ... très vite ça va devenir in-maintenable.

**Comment by demoulinflo** [comment]
Ok pour ajouter un petit texte dans la partie "A propos" (on déplacera peut être le texte dans les onglets concernés dans le contenu texte final)

**Comment by demoulinflo** [comment]
@jalazawa : Peux-tu t'en faire une proposition de texte ? Merci !

**Comment by bthieurmel** [comment]
Mis une alerte

**Comment by jalazawa** [comment]
Génial. @demoulinflo est-ce que ça te vas ? Pour moi c'est parfait.

**Comment by demoulinflo** [comment]
C'est bon pour moi ! Je trace dans les specs.

**Comment by demoulinflo** [comment]
Bon bon bon... Au final ca ne passe pas du tout cette non compatibilité IE...

Combien de temps pour corriger les "gros" bugs ?
Essentiellement du côté "analyse détaillée" me semble-t-il...

Dsl, j'ai tout essayé pour ne pas le faire :(

**Comment by bthieurmel** [comment]
Le problème c'est que IE fait office de "dinosaure" dans les navigateur web.... et que les entreprises ne sont pas au top pour les migrations / droits utilisateurs pour autoriser / changer cela.

Peux-tu nous lister l'ensemble des "bugs" observés ? (si autres que celui évoqué ci-dessus). On va regarder mais on ne peut malheureusement rien promettre....

**Comment by demoulinflo** [comment]
OK, je te liste les bugs dès que possible (fin de matinée / début d'aprèm), on verra ce qu'on peut corriger ou non...

Je suis complètement d'accord par rapport à IE... Mais IE étant le navigateur "officiel" chez Rte, ça ne passe pas trop :( On aura essayé !

**Comment by bthieurmel** [comment]
A priori, j'ai trouvé une solution... Je pourrais cependant déployer l'application corrigée uniquement demain après-midi. (Il me faut un bon réseau hors wifi et adsl pour cela....)

**Comment by demoulinflo** [comment]
Top ! 
Pas de soucis pour le déploiement demain après-midi... je ne pourrai tester que lundi, donc pas d'urgence !

**Comment by demoulinflo** [comment]
Tout semble ok !
