### ISSUE TITLE
Analyse détaillée - Sélection du tirage à visualiser - Modification

### ISSUE THREAD

**Issue by demoulinflo** [rte-antares-rpackage/bpN#96]
Pour simplifier le process vu de l'utilisateur
--> la sélection du tirage à importer est limitée à 1 tirage (-> A renommer "Tirage")
--> le champ "Tirage à visualiser" est masqué (tirage à importer = tirage à visualiser)

Je pense qu'il est intéressant de conserver le bouton d'"actualisation".
Cela permet d'éviter les chargements/traitements inutiles si l'utilisateur change le tirage et la période.

Mis à jour dans les spécifications V0.2

**Comment by jalazawa** [comment]
Si je comprends bien, on ne veut plus visualiser le tirage moyen ? actuellement on ne peut pas le faire sur l'application.

**Comment by bthieurmel** [comment]
Si tu peux toujours en ne sélectionnant rien dans la liste (et 'moyen' s'affichera)

**Comment by jalazawa** [comment]
OK, je propose une simplification, il y'a peut-être solution. 

Est-ce qu'on pourrait avoir un check box ? tirage moyen 

Si le check box est validé (plein) alors on n'affiche pas la liste "Tirage" 

![choix_scenario](https://user-images.githubusercontent.com/22026724/37196438-0eba0f9e-2377-11e8-9a23-6670f0cf2eb4.png)

Si le check box est invalidé alors on n'affiche la liste 

Un peu comme le fonctionne du deuxième axe sur le module plot 

sans validation 

![choix_scenario_1](https://user-images.githubusercontent.com/22026724/37196528-780969a4-2377-11e8-8c4c-1d0e1100bb23.png)


avec validation

![choix_scenario_2](https://user-images.githubusercontent.com/22026724/37196530-7b813404-2377-11e8-80ba-566c27f3ccdb.png)

**Comment by demoulinflo** [comment]
C'est bon pour moi.
Et si la modification proposée par @jalazawa est faisable, c'est encore mieux !

**Comment by bthieurmel** [comment]
ok

**Comment by jalazawa** [comment]
C'est Ok pour moi. 

@demoulinflo est-ce que tu peux clôturer le ticket merci ?

**Comment by demoulinflo** [comment]
Ok !
