### ISSUE TITLE
plotMap : légende : trouver une solution pour réduire la légende dans tous les cas 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#97]
Voilà ce que j'obtiens si je compare 3 cartes 

![cacher_la_legende](https://user-images.githubusercontent.com/22026724/37197267-63aefb60-237a-11e8-998b-f8151a621d26.png)

Je peux afficher la légende mais je ne peux plus la cacher. 

Le bouton pour la cacher étant en bas. 

pourrait-on avoir une autre solution ? 

bouton en haut ? 
réduction de la fenêtre de légende ? 

![cacher_la_legende_2](https://user-images.githubusercontent.com/22026724/37197314-a12979f2-237a-11e8-923d-a3f165a9e8d7.png)

**Comment by bthieurmel** [comment]
Mise en haut

**Comment by jalazawa** [comment]
Parfait.
