### ISSUE TITLE
application : performance : shinyappio : mode comparaison 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpN#99]
Je pense que cette idée peut-être un big-win (peu de développement et un grand gain). 

Maintenant qu'on importe qu'une seule année par étude, on pourrait initialiser tous les modules au démarrage. 

Pour l'instant, seul le module production est initialisé au début donc lorsqu'on clic sur Echanges, Chroniques ou Map on attend environ 15 secondes pour la création des modules. 

13 secondes pour Echanges 
17 secondes pour Chroniques 
15 secondes pour Map 

Une fois le module initialisé, il ne faut que 3 secondes pour charger et visualiser une année dans tous les modules. 

On pourrait initialiser tous les modules avec la première année afin de faire gagner 15 secondes par module à l'utilisateur. 

On pourrait garder cette possibilité d'initialiser le module (ou non) lors du lancement de l'application. 
Par défaut, non (dans antaresViz) mais on peut le faire (bpNumerique). 

Test avec 3 études sur le site web 

![performance_changement_annee_site](https://user-images.githubusercontent.com/22026724/37200682-cc5d13bc-2385-11e8-9a66-40a5da688ea5.png)

**Comment by bthieurmel** [comment]
J'ai fait exprès d'initialiser les modules uniquement quand tu arrives sur l'onglet.

Sinon, tu devra attendre l'initialisation de tous les modules, soit potentiellement une minute dans ton cas, pour voir le prodStack affiché....

**Comment by jalazawa** [comment]
Est-ce qu'on peut initialiser les modules en parallèle ?

**Comment by jalazawa** [comment]
Ce qui m'étonne un peu, c'est en local je n'ai pas du tout les mêmes performances lorsque je lance les modules en dehors de l'app. 

```R

library(antaresViz)

path<-"D:\\Users\\jalazawa\\Documents\\Dev\\PackagesR\\develop\\github\\bpN\\inst\\application_bp\\data\\Ampere_2030.h5"
setSimulationPath(path)
mydata<-readAntares(areas = "all", links = "all", mustRun = TRUE, mcYears = 1)
prodStack(mydata$areas)

system.time(prodStack(list(mydata$areas, mydata$areas, mydata$areas, mydata$areas)))
system.time(exchangesStack(list(mydata$links, mydata$links, mydata$links, mydata$links), area = "a"))
```

On est plus sur 4 à 5 secondes pour créer un shinyGadget. 

```R


> system.time(exchangesStack(list(mydata$links, mydata$links, mydata$links, mydata$links), area = "a"))

Listening on http://127.0.0.1:3366
utilisateur     système      écoulé 
       3.09        0.35        4.82 
```

**Comment by bthieurmel** [comment]
Et en lançant le module directement sur le .h5 et non sur la sortie d'un ``readAntares`` ?

````
path<-"D:\\Users\\jalazawa\\Documents\\Dev\\PackagesR\\develop\\github\\bpN\\inst\\application_bp\\data\\Ampere_2030.h5"
opts_h5 <- setSimulationPath(path)
system.time(prodStack(list(opts_h5 , opts_h5 , opts_h5 , opts_h5 )))
````

**Comment by jalazawa** [comment]
toujours plus rapide, 6 / 7 secondes au lieu de 13 / 15 

```R
> opts_h5 <- setSimulationPath(path)
> system.time(prodStack(list(opts_h5 , opts_h5 , opts_h5 , opts_h5 )))

Listening on http://127.0.0.1:3947
utilisateur     système      écoulé 
       4.26        0.28        7.42 
> opts_h5 <- setSimulationPath(path)
> system.time(prodStack(list(opts_h5 , opts_h5 , opts_h5 , opts_h5 )))

Listening on http://127.0.0.1:3947
utilisateur     système      écoulé 
       4.18        0.20        6.54 

```

**Comment by bthieurmel** [comment]
Plusieurs éléments de réponses

- l'utilisation en shiny est différente

````
library(shiny)

opts_h5 <- setSimulationPath("C:/Users/Datastorm/Documents/git/bpNumerique2018/inst/application_bp/data/Ampere_2025.h5")

params <- list(
  areas = "all", links = "all",
  clusters = "all", districts = "all",
  select = c("OV. COST", "OP. COST", "MRG. PRICE", "CO2 EMIS.", "BALANCE", "ROW BAL.", "PSP", "MISC. NDG",
             "LOAD", "H. ROR", "WIND", "SOLAR", "NUCLEAR", "LIGNITE", "COAL", "GAS", "OIL", "MIX. FUEL",
             "H. STOR", "UNSP. ENRG", "SPIL. ENRG", "LOLD", "LOLP", "AVL DTG", "DTG MRG", "MAX MRG",
             "NP COST", "NODU", "FLOW LIN.", "congestion", "effacement")
)

mod_prodStack <- prodStack(list(opts_h5, opts_h5, opts_h5, opts_h5), xyCompare = "union",
                           h5requestFiltering = list(params, params, params, params),
                           unit = "GWh", main = "Production", areas = "fr", mcYear = "1",
                           interactive = TRUE, .updateBtn = TRUE, .showCompare = FALSE,
                           .updateBtnInit = TRUE, .runApp = FALSE, 
                           language = "fr", hidden = c("stepPlot", "drawPoints", "main", 
                                                       "mcYear", "legend", "unit", "tables", "areas", "stack"))

ui <- navbarPage(
  "Test manipulateWidget",
  tabPanel(
    "Module 1",
    mwModuleUI("prod", height = "800px")
  )
)

server <- function(input, output, session) {
  mwModule("prod", mod_prodStack)
}

shinyApp(ui, server)
````

- le temps de réaction sur le serveur  ``shinyapps.io`` est clairement plus long que sur mon PC en local par exemple

- Vu que le nombre d'études est toujours variables, on est obligé d'actualiser les modules

- l'initialisation en parallèle me paraît difficilement faisable (modifications de la logique, et donc beaucoup de travail dans le code) pour peut-être un résultat décevant...

**Comment by jalazawa** [comment]
Il n'y a pas de remarque sur la performance de l'application. Je clos pour l'instant.
